###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

# Specify architecture (amd64, ppc64le, s390x) and weight to be  used for scheduling as follows : 
#   0 - Do not use
#   1 - Least preferred
#   2 - No preference
#   3 - Most preferred
arch:
  amd64: "2 - No preference"
  ppc64le: "2 - No preference"
  s390x: "2 - No preference"

credentials:
  username: admin
  password: admin

calicoctl:
  enabled: false

image:
  repository: ibmcom/web-terminal
  tag: 2.8.1-r3
  pullPolicy: IfNotPresent

service:
  type: NodePort
  externalPort: 3000

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: ""

## Configure resource requests and limits
## ref: https://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 200Mi
    cpu: 100m
  limits:
    memory: 200Mi
    cpu: 100m
