# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

image:
  pullPolicy: IfNotPresent

security:
  # Security can be flagged on for any platform, but will only work on x86 nodes.
  enabled: false
  provider: searchguard-tls
  ca:
    keystore:
      password: changeme
    truststore:
      password: changeme
    # set to `external` to use existing CA stored in Kubernetes secret to generate certs
    origin: internal
    external:
      # the secret need to be in the same namespace as the chart release
      secretName: cluster-ca-cert
      # the Kubenetes field name (key) within the specified secret that stores CA cert
      certFieldName: tls.crt
      # the Kubenets field name (key) within the specified secret that stores CA private key
      keyFieldName: tls.key
  app:
    keystore:
      password: changeme

logstash:
  replicas: 1
  name: logstash
  heapSize: "512m"
  memoryLimit: "1024Mi"
  port: 5000
  image:
    repository: "ibmcom/logstash"
    tag: "5.5.1"
  probe:
    enabled: false
    periodSeconds: 60
    minEventsPerPeriod: 1
    maxUnavailablePeriod: 5
    image:
      repository: "ibmcom/logstash-liveness-probe"
      tag: "0.1.8"

kibana:
  install: true
  replicas: 1
  name: kibana
  internal: 5601
  external: 31601
  # maximum old space size (in MB) of the V8 Javascript engine
  maxOldSpaceSize: "1024"
  memoryLimit: "1280Mi"
  image:
    repository: ibmcom/kibana
    tag: 5.5.1
  initImage:
    repository: "ibmcom/curl"
    tag: "3.6"
  routerImage:
    repository: "ibmcom/icp-router"
    tag: "2.2.0"

filebeat:
  name: filebeat-ds
  image:
    repository: "ibmcom/filebeat"
    tag: 5.5.1
  scope:
    nodes:
    namespaces:

elasticsearch:
  name: "elasticsearch"
  internalPort: 9300
  image:
    repository: "ibmcom/elasticsearch"
    tag: "5.5.1"
  pluginImage:
    repository: "ibmcom/elasticsearch-plugin-searchguard"
    tag: "1.0.0"
  pluginInitImage:
    repository: "ibmcom/searchguard-init"
    tag: "1.0.0"
  pkiInitImage:
    repository: "ibmcom/logging-pki-init"
    tag: "1.3.0"
  initImage:
    repository: "ibmcom/icp-initcontainer"
    tag: "1.0.0"

  client:
    name: client
    replicas: 1
    heapSize: "1024m"
    memoryLimit: "1536Mi"
    restPort: 9200
    antiAffinity: soft

  master:
    name: master
    # Set to the # of management (or master, if no mgmt) nodes
    replicas: 1
    heapSize: "1024m"
    memoryLimit: "1536Mi"
    antiAffinity: soft

  data:
    name: data
    # Set to the # of management (or master, if no mgmt) nodes
    replicas: 2
    heapSize: "1024m"
    memoryLimit: "2048M"
    antiAffinity: hard
    storage:
      # When true will expect a PersistentVolume
      persistent: true
      # Set to true if you are using GlusterFS or other dynamic provisioner
      useDynamicProvisioning: false
      # If not using dynamic provisioning, you can use selectors to refine the binding process.
      # These are IGNORED if using dynamic provisioning.
      selector:
        label: ""
        value: ""
      # 10Gi is not the recommended size, but rather a small default.
      # It will match much larger drives as well.
      size: 10Gi
      accessModes:
        - ReadWriteOnce
      ## Specify the storageClass name you want to use
      ## If you don't specify a storageClass name it will use the default
      storageClass: ""

curator:
  name: log-curator
  image:
    repository: "ibmcom/indices-cleaner"
    tag: 0.2
  # runs at 23:30 UTC daily
  schedule: "30 23 * * *"
  app:
    unit: days
    count: 1
  monitoring:
    unit: days
    count: 1
  watcher:
    unit: days
    count: 1

mode: standard

xpack:
  # Must be false for PPC, otherwise the log is spammed with errors
  monitoring: false
  graph: false
  reporting: false
  ml: false
  watcher: false
