dependencies:
  - name: ibm-sch
    repository: "@sch" ## where sch is based on [NAME] from the cmd: helm repo add [flags] [NAME] [URL]
    version: 1.2.0   
    alias: sch
  - name: ibm-iisee-eval-tpr
    alias: iiseetpr
    version: 1.0.3
