###############################################################################
########## IBM InfoSphere Information Server for Evaluation v11.7 #############
###############################################################################

license: "not accepted"

arch:
  amd64: "3 - Most preferred"

###############################################################################
## global persistence settings 
############################################################################### 

global:
   persistence:
      enabled: true
      useDynamicProvisioning: true 


###############################################################################
## Common image variables
###############################################################################

release:
  image:
    pullPolicy: IfNotPresent  
    repository: iighostd  
    tag: 11.7 


###############################################################################
## IIS container variables
###############################################################################

iisService:
 
  resources:
    requests: 
      cpu: "2000m"
      memory: "6000Mi"
 
  volumeClaim:
    name: "secrets-pvc"
    storageClassName: ""
    size: 1Mi 
    existingClaimName: ""
    accessMode: ReadWriteMany
   
    

###############################################################################
## Governance containers 
###############################################################################


shop4infoSolr:

  volumeClaim:
    name: "solr-pvc"
    storageClassName: ""
    size: 5Gi
    existingClaimName: ""
    accessMode: ReadWriteOnce


ugResources:
      requests:
        cpu: "500m"
        memory: "2000Mi"

solrResources:
      requests:
        cpu: "200m"
        memory: "1000Mi"
##############################################################################
## Storage for TPR subchart
##############################################################################

iiseetpr:

 cassandra: 

   volumeClaim:
      size: 5Gi
      existingClaimName: ""
      storageClassName: "" 

 zookeeper:

   volumeClaim:
      size: 5Gi
      existingClaimName: ""
      storageClassName: "" 

 kafka:

   volumeClaim:
      size: 5Gi
      existingClaimName: ""
      storageClassName: ""

 elasticsearch:

   volumeClaim:
      size: 5Gi
      existingClaimName: ""
      storageClassName: ""

 logstash:

   volumeClaim:
      size: 5Gi
      existingClaimName: ""
      storageClassName: ""

 cassandraResources:
     requests:
       cpu: "2000m"
       memory: "4000Mi"

 kafkaResources:
     requests:
       cpu: "500m"
       memory: "1000Mi"

 zookeeperResources:
     requests:
       cpu: "500m"
       memory: "2000Mi"
 ugResources:
     requests:
       cpu: "500m"
       memory: "2000Mi"

