## Arch metadata
arch:
  __metadata:
    label: "Architecture scheduling preferences"
  amd64:
    __metadata:
      name: "amd64"
      label: "amd64"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No Preference"
        value: "2 - No Preference"  
      - label: "3 - Most preferred"
        value: "3 - Most preferred"  
