# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ template "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.kibana.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: "{{ .Values.kibana.name }}"
spec:
  selector:
    app: "{{ template "fullname" . }}"
    component: "{{ .Values.kibana.name }}"
    release: "{{ .Release.Name }}"
    role: "kibana"
    heritage: "{{ .Release.Service }}"
{{- if .Values.kibana.managedMode }}
  ports:
  - port: {{ .Values.kibana.external }}
    targetPort: {{ if .Values.elasticsearch.security.enabled }}8443{{ else }}8080{{ end }}
    protocol: TCP
{{ else }}
  ports:
  - port: {{ .Values.kibana.internal }}
    protocol: TCP
    targetPort: ui
    nodePort: {{ .Values.kibana.external }}
  type: LoadBalancer
{{- end }}
