{{- if .Values.kibana.managedMode -}}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "fullname" . }}-ingress"
  annotations:
    kubernetes.io/ingress.class: "ibm-icp-management"
    icp.management.ibm.com/secure-backends: {{ if .Values.elasticsearch.security.enabled }}"true"{{ else }}"false"{{ end }}
{{- if eq .Values.elasticsearch.security.enabled false }}
    # Tells ingress to keep the /kibana context root
    icp.management.ibm.com/rewrite-target: "/"
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /kibana
        backend:
          serviceName: {{ .Values.kibana.name }}
          servicePort: {{ .Values.kibana.external }}
{{- end -}}
