# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "fullname" . }}-config"
  labels:
    app: "{{ template "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.kibana.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  kibana.yml-x86: |-
    # x86-only config. Must include refs to X-Pack.
{{ include "kibana.config" . | indent 4 }}
{{ include "kibana.xpack" . | indent 4 }}
  kibana.yml-ppc: |-
    # ppc64le-only config. Must not include refs to X-Pack.
{{ include "kibana.config" . | indent 4 }}
  kibana-entrypoint.sh: |-
    #!/bin/sh
    cd /scripts
    ./map-config.sh

    echo "Launching Kibana"
    /usr/local/bin/kibana-docker
  map-config.sh: |-
    #!/bin/bash
    # Configures a symlink from, e.g. /usr/share/elasticsearch-config-[arch] to
    # /usr/share/elasticsearch/config. The actual paths vary depending on which
    # product is being configured.

    PPCROOT=${CFG_BASEDIR}-config-ppc
    X86ROOT=${CFG_BASEDIR}-config-x86
    TARGET=${CFG_BASEDIR}/config
    MACTYPE=`uname -m`
    echo "Machine type: $MACTYPE"

    mkdir -p $TARGET 2>/dev/null

    function link {
      for i in `ls $1`; do
        echo "Linking $1/$i to $TARGET/$i"
        # Link, don't copy, so that changes on K8s side are propagated down to product
        ln -sf $1/$i $TARGET/$i
      done
    }

    [ "$MACTYPE" == "ppc64le" ] && link $PPCROOT && exit
    # Default to x86
    link $X86ROOT
