###############################################################################
######################## IBM DSX Developer Edition. ###########################
###############################################################################


###############################################################################
## Common image variables
###############################################################################
image:
  pullPolicy: "IfNotPresent"

## global persistence settings
persistence:
  useDynamicProvisioning: false

dsxservice:
  externalPort: 32443

###############################################################################
## Persistence Storage
###############################################################################

## Persistence is enabled by default, set Enabled: true to use
userHomePvc:
  name: user-home-pvc
  persistence:
    existingClaimName: ""
    storageClassName: ""
    size: "10Gi"

sparkMetricsPvc:
  name: 'spark-metrics-pvc'
  persistence:
    existingClaimName: ""
    storageClassName: ""
    size: "50Gi"


###############################################################################
## DSX Desktop Edition UX Server Continer
###############################################################################

dsxCoreContainer:

  ## UX Container Image regestry/endpoint and version (tag)
  image:
    repository: "db2eventstore/icp-dev-dsx-core"
    tag: "latest"

  ## UX Container resources, a minimum cpu request of "1000m" is required
  resources:
    requests:
      cpu: "1000m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "512Mi"


###############################################################################
## Spawner
###############################################################################

spawnerApiContainer:
  image:
    repository: "db2eventstore/icp-dev-spawner"
    tag: "v1.027"
  resources:
    requests:
      cpu: "200m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

###############################################################################
## Nginx
###############################################################################

nginxContainer:
  image:
    repository: "db2eventstore/icp-dev-nginx"
    tag: "v1.034"
  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"

###############################################################################
## Spark
###############################################################################

sparkContainer:
  image:
    repository: "db2eventstore/icp-dev-spark"
    tag: "latest"
  resources:
    requests:
      cpu: "500m"
      memory: "2048Mi"
    limits:
      cpu: "1000m"
      memory: "4096Mi"

jupyter:
  image:
    repository: "db2eventstore/icp-dev-jupyter"
    tag: "latest"

zeppelin:
  image:
    repository: "db2eventstore/icp-dev-zeppelin"
    tag: "v1.0.85"

rstudio:
  image:
    repository: "db2eventstore/icp-dev-rstudio"
    tag: "v3.17"
