name: ibm-eventstreams-dev
version: 0.1.2
description: Kafka is an open-source stream processing platform used for building real-time data pipelines and streaming apps.
icon: https://developer.ibm.com/messaging/wp-content/uploads/sites/18/2018/05/icon_dev_32_24x24.png
tillerVersion: ">=2.7.2"
keywords:
  - kafka
  - amd64
  - Tech
  - ICP
  - Integration
