###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2018. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################

###############################################################################
############################# IBM EVENT STREAMS ###############################
###############################################################################


###############################################################################
# values that are needed for all Event Streams charts
###############################################################################
global:
  #
  # settings for how Docker images are pulled
  image:
    # repository is the container repository to use, which must contain the IBM Event Streams images
    repository: ibmcom
    # pullSecret is the secret to use when pulling the image from a private registry
    #  optional when pulling from Docker registries that don't require authentication
    pullSecret:
    # pullPolicy is either IfNotPresent or Always
    #  (https://kubernetes.io/docs/concepts/containers/images/)
    pullPolicy: IfNotPresent



###############################################################################
# Kafka-specific settings
###############################################################################
kafka:
  # resource limits to apply to the Kafka broker pods
  # ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 1000m
      memory: 1Gi

  # Number of Kafka brokers in the cluster
  brokers: 3

  #
  # Config values to pass to the config file for each Kafka broker

  # If you want to run a single broker cluster, change offsetsTopicReplicationFactor to 1
  offsetsTopicReplicationFactor: 2
  minInsyncReplicas: 1
  compressionType: "producer"
  deleteTopicEnable: true
  autoCreateTopicsEnable: false

#
# Persistence settings which apply to the Kafka broker pods
persistence:
  # whether to use Persistent Volumes for the Kafka pods
  enabled: false
  # whether to use Storage Classes to dynamically create Persistent Volumes for the Kafka pods
  useDynamicProvisioning: false
  #
  # settings for the Kafka pod Persistent Volume Claims,
  #   which each pod uses for data in /var/data
  dataPVC:
    # prefix for names for this Persistent Volume Claim
    name: "datadir"
    # name of the Storage Class to use, or an empty string for no Storage Class
    storageClassName: ""
    # minimum size of the Persistent Volume
    size: 4Gi



###############################################################################
# ZooKeeper-specific settings
###############################################################################
zookeeper:
  # resource limits to apply to the ZooKeeper pods
  # ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 100m
      # memory limits are provided by the subchart and not overridden here
    requests:
      cpu: 100m
      # memory requests are provided by the subchart and not overridden here

  #
  # Persistence settings which apply to the ZooKeeper pods
  persistence:
    # whether to use Persistent Volumes for the ZooKeeper pods
    enabled: false
    # whether to use Storage Classes to dynamically create Persistent Volumes for the ZooKeeper pods
    useDynamicProvisioning: false

  #
  # settings for the ZooKeeper Persistent Volume Claims
  #  which each pod uses for data in /var/lib/zookeeper
  dataPVC:
    # prefix for names for this Persistent Volume Claim
    name: "datadir"
    # name of the Storage Class to use, or an empty string for no Storage Class
    storageClassName: ""
    # minimum size of the Persistent Volume
    size: 2Gi



###############################################################################
# Kafka external access configuration
###############################################################################
proxy:
  # whether to deploy the proxy to enable external access to Kafka
  externalAccessEnabled: false
  # Secure connection TLS for the proxy
  secureConnectionsEnabled: false
  # external IP address for access that the proxy should use
  externalEndpoint: "myserver"
# Secure connection settings for the proxy
tls:
  type: "selfsigned"
  key:
  cert:
  cacert:


###############################################################################
# license must be set to "accept" to accept the terms of the IBM license
###############################################################################

license: "not accepted"
