###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2018. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
# Defines a service to allow internal access to the UI web server
###############################################################################
{{ $namePrefix := .sch.chart.components.ui.service.name -}}
{{ $name := include "sch.names.fullCompName" (list . $namePrefix ) -}}
{{ $uiDeployment := .sch.chart.components.ui.deployment.name -}}
# Component is 'ui' as this makes up part of implementing the UI
{{ $compName := .sch.chart.components.ui.compName -}}
{{ $labels := include "sch.metadata.labels.standard" (list . $compName) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ $labels | indent 4 }}
spec:
  ports:
    - port: {{ .sch.config.ui.ports.port  }}
      targetPort: {{ .sch.config.ui.ports.targetPort }}
      protocol: TCP
      name: http-port
  selector:
    release: {{ .Release.Name | quote }}
    serviceSelector: {{ $uiDeployment | quote }}
