###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2018. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
# Defines a proxy installation to allow external HTTPS access to the REST API
###############################################################################
{{ $namePrefix := .sch.chart.components.restproxy.configMap.name -}}
{{ $name := include "sch.names.fullCompName" (list . $namePrefix) -}}
# Component is 'restproxy' as this makes up part of implementing the external access proxy
{{ $compName := .sch.chart.components.restproxy.compName -}}
{{ $labels := include "sch.metadata.labels.standard" (list . $compName) -}}
# Names of the REST service to route requests to
{{ $restService := .sch.chart.components.rest.service.name -}}
{{ $restServiceName := include "sch.names.fullCompName" (list . $restService) -}}
# Names of proxy resources for dynamic allocation
{{ $service := .sch.chart.components.restproxy.service.name -}}
{{ $serviceName := include "sch.names.fullCompName" (list . $service) -}}
###############################################################################
# Config map that defines the rest-proxy configuration
###############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ $labels | indent 4 }}
data:
  serviceName: {{ $serviceName | quote }}
  connectionTimeoutMs: "3600000"
  externalAccessEnabled: "true"
  externalHostOrIP: ""
  revision: "0"
  routes: |
    [
      {
        "Port": 0,
        "NodePort": 0,
        "Service": "{{ $restServiceName }}:{{ .sch.config.rest.ports.port  }}"
      }
    ]
  tlsEnabled: "true"
  tlsHandshakeTimeoutMs: "10000"
