###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2018. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
####################################################################################
# Defines the service that exposes the proxy enabling HTTPS access to the REST API
####################################################################################
{{- include "sch.config.init" (list . "sch.chart.config.values") -}}
{{- include "sch.config.init" (list . "rest.sch.chart.config.values") -}}
{{ $namePrefix := .sch.chart.components.restproxy.service.name -}}
{{ $name := include "sch.names.fullCompName" (list . $namePrefix) }}
# Component is 'restproxy' as this makes up part of implementing the REST API proxy
{{ $compName := .sch.chart.components.restproxy.compName -}}
{{ $labels := include "sch.metadata.labels.standard" (list . $compName) -}}
{{ $deploymentName := .sch.chart.components.rest.deployment.name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ $labels | indent 4 }}
spec:
  type: NodePort
  ports:
    - name: restendpoint
      protocol: TCP
      port: {{ .sch.config.rest.proxy.port  }}
  selector:
    release: {{ .Release.Name | quote }}
    serviceSelector: {{ $deploymentName | quote }}
