# Default values for probe_cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


#Docker image license acceptance
license: "not accepted"

image:
  repository: ibmcom/netcool-probe-messagebus
  tag: latest
  pullPolicy: IfNotPresent

netcool:
  primaryServer: NCOMS
  primaryHost: omnibus.service.netcool
  primaryPort: 4100
  backupServer: 
  backupHost: 
  backupPort: 

logstashProbe:
  enabled: true
  replicaCount: 5
  service:
    type: NodePort
    externalPort: 80

  ingress:
    enabled: false
    # Used to create Ingress record (should used with service.type: ClusterIP).
    # Uncomment to configure multiple hostnames, annotations and tls and then
    # install using helm command line.
    hosts: 
      - netcool-probe-logstash.local
    #annotations: 
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    #tls:
      # Secrets must be manually created in the namespace.
      # - secretName: logstash-probe-tls
      #   hosts:
      #     - netcool-probe-logstash.local

  # Autoscaling Configuration
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    cpuUtil: 60

prometheusProbe:
  enabled: true
  replicaCount: 1
  service:
    type: NodePort
    externalPort: 80
  ingress:
    enabled: false
    # Used to create Ingress record (should used with service.type: ClusterIP).
    # Uncomment to configure multiple hostnames, annotations and tls and then
    # install using helm command line.
    hosts: 
       - netcool-probe-prometheus.local
    #annotations:
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    #tls:
      # Secrets must be manually created in the namespace.
      # - secretName: prometheus-probe-tls
      #   hosts:
      #     - netcool-probe-prometheus.local

  # Autoscaling Configuration
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    cpuUtil: 60

probe:
  # Probe log level
  messageLevel: warn

# Resources settings
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Node affinity settings
# Specify architecture (amd64). Only amd64 arch is supported.
arch: amd64


