apiVersion: v1
kind: Service
metadata:
  name: eventstore-svc
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: eventstore
spec:
  ports:
  # this value will be replaced by the create.sh script
  - port: 1100
    targetPort: 1100
    name: server
  selector:
    app: eventstore
    component: eventstore
  # note the external IP address will be replaced by the create.sh script
  externalIPs:
    - {{ .Values.address.virtualIp }}
