kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: eventstore
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: eventstore
        chart: "{{ .Chart.Name }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
      annotations:
        productName: {{ .Chart.Name }}
        productID: IBMDb2EventStore_111_perpetual_00000
        productVersion: {{ .Chart.Version }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                  - amd64
      terminationGracePeriodSeconds: 0
      containers:
        - name: eventstore
          image: "db2eventstore/icp-dev-es:latest"
          imagePullPolicy: {{ index .Values "ibm-dsx-dev" "image" "pullPolicy" | default "IfNotPresent" | quote }}
          volumeMounts:
            - name: bluspark-logs
              mountPath: /bluspark/logs
            - name: bluspark-shared
              mountPath: /bluspark/db/shared
            - name: bluspark-ssd
              mountPath: /bluspark/db/ssd
            - name: bluspark-conf
              mountPath: /bluspark/conf
            - name: bluspark-zookeeper-data
              mountPath: /bluspark/zookeeper/store/data
          ports:
            - containerPort: 1100
              hostPort: 1100
              name: public-port
          readinessProbe:
            tcpSocket:
              port: 1100
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 1100
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
          - name: NAMESPACE
            value: {{.Release.Namespace}}
          - name: ES_EXTERNAL_PORT
            value: "1100"
      nodeSelector:
        bluspark_node: H1
      volumes:
        - name: bluspark-shared
          persistentVolumeClaim:
            claimName: "{{ .Values.ibmEsPvc.persistence.existingClaimName }}"
        - name: bluspark-ssd
          hostPath:
            path: "{{ .Values.disk.storagePath }}/eventstore/ssd"
        - name: bluspark-logs
          hostPath:
            path: "{{ .Values.disk.storagePath }}/eventstore/logs"
        - name: bluspark-conf
          hostPath:
            path: "{{ .Values.disk.storagePath }}/eventstore/conf"
        - name: bluspark-zookeeper-data
          hostPath:
            path: "{{ .Values.disk.computePath }}/eventstore/zookeeper/data"
      hostNetwork: true
