###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
apiVersion: v1
description: IBM Cloud Automation Manager - Deprecated
name: ibm-cam-prod
version: 1.2.2
tillerVersion: ">=2.5.0"
icon: https://raw.githubusercontent.com/IBM-CAMHub-Open/starterlibrary/master/images/IBM_CAM_h.png
appVersion: 2.1.0.2
deprecated: true
