# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

# Set deploy parameters:
# elasticsearch:
#   data:
#     storage:
#       persistent: true
#       useDynamicProvisioning: false
#       selector:
#         label: type
#         value: logging-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-pv-1
  labels:
    type: logging-pv
spec:
  capacity:
    storage: "30Gi"
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/icp/logging/elk-data"
