# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

image:
  __metadata:
    label: "Image"
  pullPolicy:
    __metadata:
      label: "Pull Policy"
      description: "The policy used by Kubernetes for images."
      type: "string"
      required: true
      default: "IfNotPresent"
      options:
      - label: "Never"
        value: "Never"
      - label: "IfNotPresent"
        value: "IfNotPresent"
      - label: "Always"
        value: "Always"

elasticsearch:
  security:
      # Security can be flagged on for any platform, but will only work on x86 nodes.
      __metadata:
        label: "Security"
        description: "Security can be flagged on for any platform, but will only work on x86 nodes."
      enabled:
        __metadata:
          label: "Enable Security"
          description: "If set to true, configures HTTPS/TLS and mutual certificate-based authentication for all components of the logging service."
          type: "boolean"
          required: true
          default: true
          # Provider could be marked as hidden?

kibana:
  __metadata:
    label: "Kibana"
    description: "Kibana lets you visualize your Elasticsearch data and navigate the Elastic Stack." # Taken from https://www.elastic.co/products/kibana
  replicas:
    __metadata:
      label: "Replicas"
      description: "The initial pod cluster size."
      type: "number"
      required: false
      default: 1
  name:
    __metadata:
      label: "Name"
      description: "The internal name of the Kibana cluster."
      type: "string"
      required: false
      default: "kibana"
  internal:
    __metadata:
      label: "Internal Port"
      description: "The port for container-local connections."
      type: "number"
      required: false
      default: 5601
  external:
    __metadata:
      label: "External Port"
      description: "The port used for service connections."
      type: "number"
      required: false
      default: 31601
  maxOldSpaceSize:
    __metadata:
      label: "Maximum Old Space Size"
      description: "Maximum old space size (in MB) to allocate for the V8 Javascript engine."
      type: "string"
      required: false
      default: "1024"
  memoryLimit:
    __metadata:
      label: "Memory Limit"
      description: "You can express memory as a plain integer or as a fixed-point integer using one of these suffixes: E, P, T, G, M, K. You can also use the power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki."
      type: "string"
      required: false
      default: "1280Mi"
  image:
    repository:
      __metadata:
        label: "Image"
        description: "Full repository and path to Kibana image."
        type: "string"
        required: false
        default: "ibmcom/kibana"
    tag:
      __metadata:
        label: "Image Tag"
        description: "The tag identifying which Kibana image to deploy."
        type: "string"
        required: false
        default: "5.5.1"
  routerImage:
    repository:
      __metadata:
        label: "Proxy Router Image"
        description: "Full repository and path to the Kibana proxy image."
        type: "string"
        required: false
        default: "ibmcom/icp-router"
    tag:
      __metadata:
        label: "Proxy Router Image Tag"
        description: "The tag identifying which Kibana proxy image to deploy."
        type: "string"
        required: false
        default: "2.2.0"

xpack:
  __metadata:
    label: "Xpack"
    description: "XPack is a [separately-licensed feature](https://www.elastic.co/products/x-pack) of Elastic products. Please see official documentation for more information. Without a license the features are only enabled for a trial basis, and by default the XPack features are disabled in this chart.

    _Note: All features&mdash;including security or authentication services&mdash;in XPack are not related to any services offered by IBM Cloud Private._"
  monitoring:
    __metadata:
      label: "Monitoring"
      description: "[Link to official documentation](https://www.elastic.co/guide/en/kibana/5.5/xpack-monitoring.html)"
      type: "boolean"
      required: true
      default: false
  graph:
    __metadata:
      label: "Graph"
      description: "[Link to official documentation](https://www.elastic.co/guide/en/kibana/5.5/xpack-graph.html)"
      type: "boolean"
      required: true
      default: false
  reporting:
    __metadata:
      label: "Reporting"
      description: "[Link to official documentation](https://www.elastic.co/guide/en/kibana/5.5/xpack-reporting.html)"
      type: "boolean"
      required: true
      default: false
  ml:
    __metadata:
      label: "Ml"
      description: "[Link to official documentation](https://www.elastic.co/guide/en/kibana/5.5/xpack-ml.html)"
      type: "boolean"
      required: true
      default: false
