# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

searchguard:
  dynamic:
    authc:
      clientcert_auth_domain:
        enabled: true
        order: 1
        http_authenticator:
          type: clientcert
          config:
            username_attribute: CN
          challenge: false
        authentication_backend:
          type: noop
    http:
      anonymous_auth_enabled: false
