###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

## Metadata for WAS VM Quickstarter

global:
  image:
    secretName:
      __metadata:
        name: "Image Pull Secret Name"
        label: "Image Pull Secret Name (see help -->)"
        description: "Type `default` to use your namespace default service account image pull secret or enter your image pull secret name here. See the 'Add ImagePullSecrets to a service account' Kubernetes documentation for more information on generating image pull secrets and how to patch the namespace default service account with an image pull secret."
        type: "string"
        immutable: false
        required: false

arch:
  __metadata:
    label: "Architecture Scheduling Preferences"
  amd64:
    __metadata:
      name: "amd64"
      label: "amd64"
      description: "Architecture preference for WAS VM Quickstarter images."
      type: "string"
      immutable: false
      required: true
      options:
        - label: "3 - Most preferred"
          value: "3 - Most preferred"

image:
  __metadata:
    label: "Image Policy"
  pullPolicy:
    __metadata:
      label: "Pull Policy"
      description: "Pull policy for the WAS VM Quickstarter images"
      type: "string"
      immutable: false
      required: true
      options:
        - label: "Always"
          value: "Always"
        - label: "Never"
          value: "Never"
        - label: "IfNotPresent"
          value: "IfNotPresent"


environment:
  __metadata:
    label: "Environment"
    description: "The environment name defining this WAS VM Quickstarter Helm release"
  name:
    __metadata:
      label: "Environment Name"
      description: "WAS VM Quickstarter Environment Name."
      type: "string"
      immutable: true
      required: true

cam:
  __metadata:
    label: "Cloud Automation Manager"
    description: "Parameters for Cloud Automation Manager."
  ip:
    __metadata:
      label: "IP Address"
      description: "IP address of Cloud Automation Manager"
      type: "string"
      required: true
  port:
    __metadata:
      label: "Port"
      description: "CAM port address."
      type: "number"
      required: true
  user:
    __metadata:
      label: "User Name"
      description: "CAM administrator user name."
      type: "string"
      required: true
  password:
    __metadata:
      label: "Password"
      description: "CAM administrator password."
      type: "password"
      required: true
  cloudConnectionName:
    __metadata:
      label: "Cloud Connection Name"
      description: "CAM Cloud Connection name."
      type: "string"
      required: true
  contentRuntimeName:
    __metadata:
      label: "Content Runtime Name"
      description: "CAM Content Runtime name."
      type: "string"
      required: true

vsphere:
  __metadata:
    label: "vSphere"
    description: "Parameters for target vSphere environment."
  osImage:
    __metadata:
      label: "OS Image"
      description: "OS Image name used to provision WAS VM Quickstarter VMs."
      type: "string"
      required: true
  osAdminUser:
    __metadata:
      label: "OS Admin User Name"
      description: "OS administrator user name."
      type: "string"
      required: true
  osAdminPassword:
    __metadata:
      label: "OS Admin Password"
      description: "OS administrator password."
      type: "password"
      required: true
  rootDiskSize:
    __metadata:
      label: "Root Disk Size"
      description: "Size of the root disk on the OS image used to provision WAS VM Quickstarter VMs."
      type: "number"
      required: true
  rootDiskDatastore:
    __metadata:
      label: "Root Disk Data Store Name"
      description: "Name of the data store hosting the root disk."
      type: "string"
      required: true
  resourcePool:
    __metadata:
      label: "Resource Pool Name"
      description: "Name of the resource pool to provision new WAS VM Quickstarter VMs."
      type: "string"
      required: true
  folder:
    __metadata:
      label: "Folder Name"
      description: "Name of the vSphere folder to provision new WAS VM Quickstarter VMs."
      type: "string"
      required: true
  domain:
    __metadata:
      label: "Domain Name"
      description: "Name of the vSphere domain to provision new WAS VM Quickstarter VMs."
      type: "string"
      required: true
  datacenter:
    __metadata:
      label: "Datacenter Name"
      description: "Name of the vSphere datacenter to provision new WAS VM Quickstarter VMs."
      type: "string"
      required: true
  networkInterfaceLabel:
    __metadata:
      label: "Network Interface Label"
      description: "Name of the vSphere network interface label to use for WAS VM Quickstarter VMs."
      type: "string"
      required: true
  dnsServers:
    __metadata:
      label: "DNS Servers"
      description: "List of DNS servers to use for WAS VM Quickstarter VMs."
      type: "string"
      required: true
  dnsSuffixes:
    __metadata:
      label: "DNS Suffixes"
      description: "List of DNS domain suffixes to use for WAS VM Quickstarter VMs."
      type: "string"
      required: true
  ipv4Gateway:
    __metadata:
      label: "IPv4 Gateway"
      description: "IP address of the IPv4 gateway to use for WAS VM Quickstarter VMs."
      type: "string"
      required: true
  ipv4PrefixLength:
    __metadata:
      label: "IPv4 Prefix Length"
      description: "Prefix length of the IPv4 gateway to use for WAS VM Quickstarter VMs."
      type: "number"
      required: true
  ipPool:
    __metadata:
      label: "IP Pool List"
      description: "List of IPs configured in vSphere to use for WAS VM Quickstarter VMs.  The list needs to be comma separated, for example: 10.2.3.2,10.2.3.3,10.2.3.4"
      type: "string"
      required: true

devops:
  __metadata:
    label: "DevOps"
    description: "Parameters for WAS VM Quickstarter DevOps image."
  image:
    __metadata:
      description: "Docker image parameters for WAS VM Quickstarter DevOps image."
    repository:
      __metadata:
        label: "Image Repository"
        description: "WAS VM Quickstarter Devops image repository."
        type: "string"
        required: true
    tag:
      __metadata:
        label: "Image Tag"
        description: "Use the image tagged with the matching string."
        type: "string"
        required: false

cloudsm:
  __metadata:
    label: "Service Management"
    description: "Parameters for WAS VM Quickstarter service management image."
  image:
    __metadata:
      description: "Docker image parameters for WAS VM Quickstarter service management image."
    repository:
      __metadata:
        label: "Image Repository"
        description: "WAS VM Quickstarter Service Management image repository."
        type: "string"
        required: true
    tag:
      __metadata:
        label: "Image Tag"
        description: "Use the image tagged with the matching string."
        type: "string"
        required: false
  user:
    __metadata:
      label: "Functional User Name"
      description: "Functional user name for WAS VM Quickstarter service management applications."
      type: "string"
      required: true
  password:
    __metadata:
      label: "Functional ID Password"
      description: "Functional password for WAS VM Quickstarter service management applications."
      type: "password"
      required: true
  capacity:
    __metadata:
      label: "Capacity"
      description: "Capacity of target environment, specified in service blocks."
      type: "number"
      required: true


broker:
  __metadata:
    description: "Parameters for WAS VM Quickstarter Broker image."
  image:
    __metadata:
      description: "Docker image parameters for the WAS VM Quickstarter broker image."
    repository:
      __metadata:
        label: "Image Repository"
        description: "WAS VM Quickstarter broker image repository."
        type: "string"
        required: true
    tag:
      __metadata:
        label: "Image Tag"
        description: "Use image tagged with the matching string."
        type: "string"
        required: false
  ingress:
    path:
      __metadata:
        label: "Ingress Path"
        description: "Ingress path to the broker container."
        type: "string"
        required: true
  user:
    __metadata:
      label: Functional User Name"
      description: "Functional user name for the WAS VM Quickstarter broker application."
      type: "string"
      required: true
  password:
    __metadata:
      label: "Functional ID Password"
      description: "Functional password for WAS VM Quickstarter broker application."
      type: "password"
      required: true
  provider:
    __metadata:
      description: "WAS VM Quickstarter Admin Credentials"
    user:
      __metadata:
        label: "WAS VM Quickstarter Admin User Name"
        description: "WAS VM Quickstarter administrator user name"
        type: "string"
        required: true
    password:
      __metadata:
        label: "WAS VM Quickstarter Admin Password"
        description: "WAS VM Quickstarter administrator password"
        type: "password"
        required: true

console:
  __metadata:
    description: "Parameters for WAS VM Quickstarter Console image."
  image:
    __metadata:
      description: "Docker image parameters for WAS VM Quickstarter console image."
    repository:
      __metadata:
        label: "Image Repository"
        description: "WAS VM Quickstarter console image repository."
        type: "string"
        required: true
    tag:
      __metadata:
        label: "Image Tag"
        description: "Use the image tagged with the matching string."
        type: "string"
        required: false
  ingress:
    path:
      __metadata:
        label: "Ingress Path"
        description: "Ingress path to the console container."
        type: "string"
        required: true

couchdb:
  __metadata:
    label: "CouchDB"
    description: "Parameters for WAS VM Quickstarter CouchDB image."
  adminUsername:
    __metadata:
      label: "Admin User Name"
      description: "WAS VM Quickstarter CouchDB administrator user name."
      type: "string"
      required: true
  adminPassword:
    __metadata:
      label: "Admin Password"
      description: "WAS VM Quickstarter CouchDB administrator password."
      type: "password"
      required: true
  persistentVolume:
    __metadata:
      description: "CouchDB Persistent Volume Detail"
    useDynamicProvisioning:
      __metadata:
        label: "Use Dynamic Provisioning"
        description: "Indicator of dynamic or static provisioning."
        type: "boolean"
        required: false
    size:
      __metadata:
        label: "Size"
        description: "Persistent volume size."
        type: "string"
        required: true
    storageClass:
      __metadata:
        label: "Storage Class"
        description: "Persistent volume storage class"
        type: "string"
        required: false
  image:
    __metadata:
      description: "Docker image parameters for WAS VM Quickstarter CouchDB image."
    repository:
      __metadata:
        label: "Image Repository"
        description: "WAS VM Quickstarter CouchDB image repository."
        type: "string"
        required: true
    tag:
      __metadata:
        label: "Image Tag"
        description: "Use the image tagged with the matching string."
        type: "string"
        required: false

iam:
  __metadata:
    label: "IAM Service"
    description: "Identity and Access Management (IAM) service connectivity parameters."
  clientId:
    __metadata:
      label: "OAuth ClientId"
      description: "IAM OAuth client ID"
      type: "string"
      required: true
  clientSecret:
    __metadata:
      label: "OAuth Client Secret"
      description: "IAM OAuth client secret"
      type: "string"
      required: true
  endpoint:
    __metadata:
      label: "Endpoint"
      description: "IAM endpoint address. For example: https://<master_ip>:8443"
      type: "string"
      required: true

migration:
  __metadata:
    description: "Configuration of the WAS migration feature."
  enabled:
    __metadata:
      label: "Enable Migration"
      description: "Enable migration"
      type: "boolean"
      required: false
  mountPoint:
    __metadata:
      label: "Mount Point"
      description: "Path to mount the migration script to the WAS VM Quickstarter VMs."
      type: "string"
      required: false
  serverAddress:
    __metadata:
      label: "NFS Server URL"
      description: "NFS server URL"
      type: "string"
      required: false
