###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

environment:
  name: CAM

cam:
  ip: ""
  port: 30000
  user: admin
  password: ""
  cloudConnectionName: "vm-quickstarter-connection"
  contentRuntimeName: "vm-quickstarter-runtime"

vsphere:
  osImage: myImage
  osAdminUser: "root"
  osAdminPassword: "myPassword"
  rootDiskSize: "25"
  rootDiskDatastore: "myDataStore"
  resourcePool: "myResourcePool"
  folder: "myFolder"
  domain: "myDomain"
  datacenter: "myDatacenter"
  networkInterfaceLabel: "myNetwork"
  dnsServers:
    - 8.8.8.8
  dnsSuffixes:
    - ipc.local
  ipv4Gateway: "10.2.3.1"
  ipv4PrefixLength: 24
  ipPool: "10.2.3.2,10.2.3.3,10.2.3.4"

console:
  image:
    repository: "ibmcom/wasaas-console"
    tag: "1.0"
  ingress:
    path: "/wasaas-console/"

broker:
  image:
    repository: "ibmcom/wasaas-wasdevaas"
    tag: "1.0"
  ingress:
    path: "/wasaas-broker/"
    
  user: wasaasbroker
  password: ""
  
  provider:
    user: admin
    password: ""


cloudsm:
  image:
    repository: "ibmcom/wasaas-cloudsm"
    tag: "1.0"

  user: wasaasservice
  password: ""

  capacity: 10
      
devops:
  image:
    repository: "ibmcom/wasaas-devops"
    tag: "1.0"

couchdb:
    image:
      repository: couchdb
      tag: 2.1.1

    adminUsername: admin
    adminPassword: ""

    persistentVolume:
      useDynamicProvisioning: false
      size: 10Gi
      storageClass: ""
      
iam:
  clientId: "wasaas-broker"
  clientSecret: ""
  endpoint: ""
      
migration:
    enabled: false
    mountPoint: ""
    serverAddress: ""

image:
  pullPolicy: Always

global:
  image:
    secretName: ""
    
arch: 
  amd64: "3 - Most preferred"

