apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cassandra-jvm-opts
  labels:
     app: {{ template "fullname" . }}-cassandra-jvm-opts
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}"
data:
  cassandra-jvm.options: |
    -XX:+UseParNewGC
    -XX:+UseConcMarkSweepGC
    -XX:+CMSParallelRemarkEnabled
    -XX:SurvivorRatio=8
    -XX:MaxTenuringThreshold=1
    -XX:CMSInitiatingOccupancyFraction=75
    -XX:+UseCMSInitiatingOccupancyOnly
    -XX:CMSWaitDuration=10000
    -XX:+CMSParallelInitialMarkEnabled
    -XX:+CMSEdenChunksRecordAlways
    # some JVMs will fill up their heap when accessed via JMX, see CASSANDRA-6541
    -XX:+CMSClassUnloadingEnabled
    -XX:+PrintGCDetails
    -XX:+PrintGCDateStamps
    -XX:+PrintHeapAtGC
    -XX:+PrintTenuringDistribution
    -XX:+PrintGCApplicationStoppedTime
    -XX:+PrintPromotionFailure
    #-XX:PrintFLSStatistics=1
    #-Xloggc:/var/log/cassandra/gc.log
    -XX:+UseGCLogFileRotation
    -XX:NumberOfGCLogFiles=10
    -XX:GCLogFileSize=10M
