{{- include "sch.config.init" (list . "iiseesub.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.elasticsearch.name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-elasticsearch
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-elasticsearch
    component: {{ .Release.Name }}-{{ .Chart.Name }}-elasticsearch
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ include "sch.names.appName" (list .) | quote }}
    release: {{ .Release.Name }}
    component: {{ $compName | quote }}
  ports:
  - name: http
    port: 9200
    protocol: TCP
  type: NodePort
