{{- include "sch.config.init" (list . "iiseesub.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.elasticsearch.name -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
    role: client
spec:
  selector:
    matchLabels:
     release: "{{ .Release.Name }}"
     app: {{ include "sch.names.appName" (list .) | quote }}
     component: "{{ $compName }}"
  replicas: 1
  template:
    metadata:
      labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 8 }}
        role: client
      annotations:
{{- include "sch.metadata.annotations.metering" (list . .sch.chart.metering) | indent 8 }}
    spec:
      affinity:
{{- include "nodeaffinity" . | indent 6 }}
      hostname: elasticsearch
      containers:
        - name: elasticsearch
          securityContext:
            capabilities:
              add:
                - AUDIT_CONTROL
                - CHOWN
                - FOWNER
                - FSETID
                - IPC_LOCK
                - IPC_OWNER
                - LINUX_IMMUTABLE
                - MAC_ADMIN
                - MAC_OVERRIDE
                - NET_ADMIN
                - NET_BIND_SERVICE
                - SETGID
                - SETFCAP
                - SETPCAP
                - SYS_ADMIN
                - SYS_BOOT
                - SYS_MODULE
                - SYS_PACCT
                - SYS_RAWIO
                - SYS_RESOURCE
          image: {{ .Values.elasticsearch.image }}  
          imagePullPolicy: IfNotPresent
          resources:
            requests:
               memory: "{{ .Values.ugResources.requests.memory }}"
               cpu: "{{ .Values.ugResources.requests.cpu }}"
          env:
          - name: CLUSTER_NAME
            value: "es-cluster"
          - name: "ES_JAVA_OPTS"
            value: "-Xms512m -Xmx512m"
          - name: NODE_MASTER
            value: "true"
          - name: NODE_DATA
            value: "true"
          - name: HTTP_ENABLE
            value: "true"
          ports:
          - containerPort: 9200
            name: http
            protocol: TCP
          - containerPort: 9300
            name: transport
            protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-pv-volume
            - name: config-volume
              mountPath: /usr/share/elasticsearch/config/log4j2.properties
              subPath: log4j2.properties
          readinessProbe:
            tcpSocket:
              port: 9200
            periodSeconds: 40
            initialDelaySeconds: 20
            timeoutSeconds: 20
            failureThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 9200
            periodSeconds: 60
            initialDelaySeconds: 40
            timeoutSeconds: 30
            failureThreshold: 3
      volumes:
        - name: es-pv-volume
          persistentVolumeClaim:
            {{- if .Values.elasticsearch.volumeClaim.existingClaimName }}
            claimName: {{ .Values.elasticsearch.volumeClaim.existingClaimName }}
            {{- else }} 
            claimName: {{ .Release.Name }}-{{ .Values.elasticsearch.volumeClaim.name }}
            {{- end }}
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-es 
