apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-es
  labels:
     app: {{ template "fullname" . }}-es
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}"
data:
  log4j2.properties: |-
    status = error
    appender.console.type = Console
    appender.console.name = console
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] %marker%m%n
    rootLogger.level = warn
    rootLogger.appenderRef.console.ref = console
    #end cm
