{{- include "sch.config.init" (list . "iiseesub.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.kafka.name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-shop4info-kafka
  labels:
    component: {{ .Release.Name }}-{{ .Chart.Name }}-shop4info-kafka
    app: {{ .Release.Name }}-{{ .Chart.Name }}-shop4info-kafka
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  selector:
    app: {{ include "sch.names.appName" (list .) | quote }}
    release: {{ .Release.Name }}
    component: {{ $compName | quote }}
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
