{{- include "sch.config.init" (list . "iiseesub.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.kafka.name -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
spec:
  selector:
    matchLabels:
     release: "{{ .Release.Name }}"
     app: {{ include "sch.names.appName" (list .) | quote }}
     component: "{{ $compName }}"
  replicas: 1
  template:
    metadata:
      labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 8 }}
      annotations:
{{- include "sch.metadata.annotations.metering" (list . .sch.chart.metering) | indent 8 }}
    spec:
      affinity:
{{- include "nodeaffinity" . | indent 6 }}
      containers:
        - name: shop4info-kafka
          image: {{ .Values.kafka.image }} 
          imagePullPolicy: IfNotPresent
          resources:
            requests:
               memory: "{{ .Values.kafkaResources.requests.memory }}"
               cpu: "{{ .Values.kafkaResources.requests.cpu }}"
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: {{ .Release.Name }}-shop4info-kafka
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: {{ .Release.Name }}-zookeeper:2181
            - name: KAFKA_CREATE_TOPICS
              value: social:1:1,igc-kg-bridge-out:1:1
          volumeMounts:
            - mountPath: /kafka
              name: kafka-pv-volume
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 20
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 10
      volumes:
        - name: kafka-pv-volume
          persistentVolumeClaim:
            {{- if .Values.kafka.volumeClaim.existingClaimName }}
            claimName: {{ .Values.kafka.volumeClaim.existingClaimName }}
           {{- else }} 
            claimName: {{ .Release.Name }}-{{ .Values.kafka.volumeClaim.name }}
           {{- end }} 
