{{- include "sch.config.init" (list . "iiseesub.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.kibana.name -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
spec:
  selector:
    matchLabels:
     release: "{{ .Release.Name }}"
     app: {{ include "sch.names.appName" (list .) | quote }}
     component: "{{ $compName }}"
  template:
    metadata:
      labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 8 }}
      annotations:
{{- include "sch.metadata.annotations.metering" (list . .sch.chart.metering) | indent 8 }}
    spec:
      affinity:
{{- include "nodeaffinity" . | indent 6 }}
      containers:
      - name: kibana
        image: {{ .Values.kibana.image }}  
        imagePullPolicy: IfNotPresent
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://{{ .Release.Name }}-{{ .Chart.Name }}-elasticsearch:9200"
        ports:
        - containerPort: 5601
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 5601
          initialDelaySeconds: 60
        readinessProbe:
          tcpSocket:
            port: 5601
          initialDelaySeconds: 30
