{{- include "sch.config.init" (list . "iiseesub.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.kibana.name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-kibana
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-kibana
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
  selector:
    app: {{ include "sch.names.appName" (list .) | quote }}
    release: {{ .Release.Name }}
    component: {{ $compName | quote }}
