{{- include "sch.config.init" (list . "iiseesub.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.logstash.name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-logstash
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-logstash
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: {{ include "sch.names.appName" (list .) | quote }}
    release: {{ .Release.Name }}
    component: {{ $compName | quote }}

