apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-logstash
  labels:
     app: {{ template "fullname" . }}-logstash
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}" 
data:
  logstash.conf: |-
    input {
      file {
        type => "app"
        path => "/var/log/containers/*.log"
        codec => json {
          charset => "UTF-8"
        }
      }
      file {
        type => "system"
        path => "/var/log/hostnode/messages"
        start_position => "beginning"
      }
    }

    filter {
      if [type] == "kube-logs" {

        mutate {
          rename => ["log", "message"]
        }

        date {
          match => ["time", "ISO8601"]
          remove_field => ["time"]
        }

        grok {
            match => { "source" => "/var/log/containers/%{DATA:pod_name}_%{DATA:namespace}_%{GREEDYDATA:container_name}-%{DATA:container_id}.log" }
            remove_field => ["source"]
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["{{ .Release.Name }}-{{ .Chart.Name }}-elasticsearch:9200"]
        user => "elastic"
        password => "changeme"
      }
    }
  logstash.yml: |-
     http.host: "0.0.0.0"
     path.config: /usr/share/logstash/pipeline
     xpack.monitoring.elasticsearch.url: http://{{ .Release.Name }}-{{ .Chart.Name }}-elasticsearch:9200
     xpack.monitoring.elasticsearch.username: logstash_system
     xpack.monitoring.elasticsearch.password: changeme
