{{- include "sch.config.init" (list . "iiseesub.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.logstash.name -}}
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
spec:
  selector:
    matchLabels:
     release: "{{ .Release.Name }}"
     component: "{{ $compName }}"
     app: {{ include "sch.names.appName" (list .) | quote }}
  template:
    metadata:
      labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 8 }}
      annotations:
{{- include "sch.metadata.annotations.metering" (list . .sch.chart.metering) | indent 8 }}
    spec:
      affinity:
{{- include "nodeaffinity" . | indent 6 }}
      hostname: logstash
      securityContext:
        runAsUser: 0
      containers:
        - name: logstash
          image: {{ .Values.logstash.image }}  
          imagePullPolicy: IfNotPresent
          resources:
            requests:
               memory: "{{ .Values.ugResources.requests.memory }}"
               cpu: "{{ .Values.ugResources.requests.cpu }}"
          volumeMounts:
            - mountPath: /usr/share/logstash/data
              name: logstash-pv-volume
            - name: logstash-config
              mountPath: /opt/logstash/pipeline/logstash.conf
              subPath: logstash.conf
            - name: logstash-config
              mountPath: /opt/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: varlog
              mountPath: /var/log/containers
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: logstash-pv-volume
          persistentVolumeClaim:
            {{- if .Values.logstash.volumeClaim.existingClaimName }}
            claimName: {{ .Values.logstash.volumeClaim.existingClaimName }}
            {{- else }} 
            claimName: {{ .Release.Name }}-{{ .Values.logstash.volumeClaim.name }}
            {{- end }} 
        - name: logstash-config
          configMap:
            name: {{ .Release.Name }}-logstash
        - name: varlog
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
