{{ if and .Values.global.persistence.enabled (not .Values.zookeeper.volumeClaim.existingClaimName) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.zookeeper.volumeClaim.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-zookeeper
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.global.persistence.useDynamicProvisioning }}
  ## if present, use the storageClassName from the values.yaml, else use the
  ## default storageClass setup by kube Administrator
  ##
  ## setting storageClassName to nil means use the default storage class
  storageClassName: {{ default nil .Values.zookeeper.volumeClaim.storageClassName | quote }}
  {{- else }}
  ## disable dynamic provisioning
  storageClassName: ""
  {{- end }}
  accessModes:
     - {{ .Values.zookeeper.volumeClaim.accessMode }} 
  resources:
    requests:
      storage: {{ .Values.zookeeper.volumeClaim.size }}
  {{- if (not .Values.global.persistence.useDynamicProvisioning ) }}
  selector:
    matchLabels:
      assign-to: "{{ .Release.Name }}-zookeeper"
  {{- end }}
 {{- end }}
