{{- include "sch.config.init" (list . "iiseesub.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.zookeeper.name -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
spec:
  selector:
    matchLabels:
     release: "{{ .Release.Name }}"
     app: {{ include "sch.names.appName" (list .) | quote }}
     component: "{{ $compName }}"
  replicas: 1
  template:
    metadata:
      labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 8 }}
      annotations:
{{- include "sch.metadata.annotations.metering" (list . .sch.chart.metering) | indent 8 }} 
    spec:
      affinity:
{{- include "nodeaffinity" . | indent 6 }}
      hostname: zookeeper
      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image }}  
          imagePullPolicy: IfNotPresent
          resources:
            requests:
               memory: "{{ .Values.zookeeperResources.requests.memory }}"
               cpu: "{{ .Values.zookeeperResources.requests.cpu }}"
          ports:
            - containerPort: 2181
          volumeMounts:
            - mountPath: /opt/zookeeper-3.4.9/data
              name: zookeeper-pv-volume
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 20
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 10
      volumes:
      - name: zookeeper-pv-volume
        persistentVolumeClaim:
          {{- if .Values.zookeeper.volumeClaim.existingClaimName }}
          claimName: {{ .Values.zookeeper.volumeClaim.existingClaimName }}
          {{- else }}  
          claimName: {{ .Release.Name }}-{{ .Values.zookeeper.volumeClaim.name }}
          {{- end }}  
