{{- include "sch.config.init" (list . "iisee.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.finley.name -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
spec:
  selector:
    matchLabels:
     release: "{{ .Release.Name }}"
     component: "{{ $compName }}"
     app: {{ include "sch.names.appName" (list .) | quote }}
  replicas: 1
  template:
    metadata:
      labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 8 }}
      annotations:
{{- include "sch.metadata.annotations.metering" (list . .sch.chart.metering) | indent 8 }}
    spec:
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      hostname: finley
      containers:
      - name: finley-ml
        image: {{ .Values.release.image.repository }}/iisee-eval-finley:{{ .Values.release.image.tag }}
        imagePullPolicy: {{ .Values.release.image.pullPolicy }}
        resources:
            requests:
               memory: "{{ .Values.ugResources.requests.memory }}"
               cpu: "{{ .Values.ugResources.requests.cpu }}" 
        ports:
        - containerPort: 5000
        volumeMounts:
            - name: config-volume
              mountPath: /finley/config.ini
              subPath: config.ini
        livenessProbe:
            failureThreshold: 15
            httpGet:
              path: /health
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 60
        readinessProbe:
            httpGet:
              path: /health
              port: 5000
              scheme: HTTP
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-finley
