apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-finley
  labels:
     app: {{ template "fullname" . }}-finley
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}" 
data:
  config.ini: |-
    [restAPI]
    domainURL = {{ .Release.Name }}-iis-service:9443
    username = isadmin
    password = P455w0rd

    [kafka]
    KAFKA_SERVER = {{ .Release.Name }}-iisdocker:59092
    KAFKA_TOPIC = IgcUnifiedGovEvents
    retrain_threshold = 1
    reconnect_threshold = 360

    [log]
    log_file = PredictFinley.log
    log_size = 52428800
    log_level = INFO
