{{- include "sch.config.init" (list . "iisee.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.haproxy.name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-haproxy
  labels:
    app: {{ template "fullname" . }}-haproxy
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ include "sch.names.appName" (list .) | quote }}
    release: {{ .Release.Name }}
    component: {{ $compName | quote }}
  type: NodePort
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443

