apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-haproxy-configmap
  labels:
     app: {{ template "fullname" . }}-haproxy-configmap 
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}" 
data:
  haproxy.cfg: |
    #---------------------------------------------------------------------
    # Example configuration for a possible web application.  See the
    # full configuration options online.
    #
    #   http://haproxy.1wt.eu/download/1.4/doc/configuration.txt
    #
    #---------------------------------------------------------------------
    #---------------------------------------------------------------------
    # Global settings
    #---------------------------------------------------------------------
    global
        # to have these messages end up in /var/log/haproxy.log you will
        # need to:
        #
        # 1) configure syslog to accept network log events.  This is done
        #    by adding the '-r' option to the SYSLOGD_OPTIONS in
        #    /etc/sysconfig/syslog
        #
        # 2) configure local2 events to go to the /var/log/haproxy.log
        #   file. A line like the following can be added to
        #   /etc/sysconfig/syslog
        #
        #    local2.*                       /var/log/haproxy.log
        #
        log         127.0.0.1 local2
       # chroot      /var/lib/haproxy
        pidfile     /var/run/haproxy.pid
        maxconn     4000
       # user        haproxy
       # group       haproxy
        daemon
        ssl-default-bind-options no-sslv3
        ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
        ssl-default-server-options no-sslv3
        ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
        tune.ssl.default-dh-param 2048
        # turn on stats unix socket
        # stats socket /var/lib/haproxy/stats
        stats socket /usr/local/etc/haproxy/admin.sock mode 660 level admin 
    #---------------------------------------------------------------------
    # common defaults that all the 'listen' and 'backend' sections will
    # use if not designated in their block
    #---------------------------------------------------------------------
    defaults
        mode                    http
        log                     global
        option                  httplog
        option                  dontlognull
        option http-server-close
        option forwardfor       except 127.0.0.0/8
        option                  redispatch
        retries                 3
        timeout http-request    10s
        timeout queue           1m
        timeout connect         10s
        timeout client          1m
        timeout server          1m
        timeout http-keep-alive 10s
        timeout check           10s
        maxconn                 3000
    #---------------------------------------------------------------------
    # main frontend which proxys to the backends
    #---------------------------------------------------------------------
    frontend https
        bind *:443 ssl crt /etc/ssl/certs/haproxy-host.pem 
        reqadd X-Forwarded-Proto:\ https

        # Containerized UIs ACLs (paths)
        acl shop4info-ui       path_beg     /ibm/iis/shop4info

        # Containerized APIs ACLs (paths)
        acl shop4info-server   path_beg     /ibm/iis/api/shop4info
        acl social_serv        path_beg     /ibm/iis/api/social
        acl catalog_search     path_beg     /ibm/iis/api/catalog_search
        acl user_prefs         path_beg     /ibm/iis/api/user_prefs
        acl app_config         path_beg     /ibm/iis/api/app_config
        acl is-dfd-ui          path_beg     /ibm/iis/dscdesigner

        # Backend calls
        default_backend   iis_backend
        use_backend       shop4info-https     if    shop4info-server
        use_backend       social-http         if    social_serv
        use_backend       shop4info-ui        if    shop4info-ui
        use_backend       catalog-http        if    catalog_search
        use_backend       user_prefs          if    user_prefs
        use_backend       app_config          if    app_config
        use_backend       is-thin             if    is-dfd-ui
    #---------------------------------------------------------------------
    # static backend for serving up images, stylesheets and such
    #---------------------------------------------------------------------
    #backend static
    #    balance     roundrobin
    #    server      static 127.0.0.1:4331 check
    #---------------------------------------------------------------------
    # round robin balancing between the various backends
    #---------------------------------------------------------------------
    backend iis_backend
        balance roundrobin
        redirect scheme https if !{ ssl_fc }
        #REPLACE_IP is private IP of this node
        server    iis                  {{ .Release.Name }}-iis-service:9443 ssl verify none

    backend is-thin
        balance roundrobin
        redirect scheme https if !{ ssl_fc }
        #REPLACE_IP is private IP of this node
        server    iis                  {{ .Release.Name }}-iis-service:9443 ssl verify none 

    backend shop4info-http
        #REPLACE_IP is private IP of this node
        server    shop4info-http       {{ template "fullname" . }}-shop4info-server:9080

    backend shop4info-https
        balance roundrobin
        redirect scheme https if !{ ssl_fc }
        #REPLACE_IP is private IP of this node
        reqirep ^([^\ :]*)\ /ibm/iis/api/shop4info(/.*)? \1\ /shop4info\2
        server    shop4info-server     {{ template "fullname" . }}-shop4info-server:9443 ssl verify none

    backend shop4info-ui
        balance roundrobin
        redirect scheme https if !{ ssl_fc }
        #REPLACE_IP is private IP of this node
        server    shop4info-ui         {{ template "fullname" . }}-shop4info-demoapp:443 ssl verify none

    backend social-http
        balance roundrobin
        #REPLACE_IP is private IP of this node
        server    social-server        {{ template "fullname" . }}-gov-social-service:9080

    backend user_prefs
        balance roundrobin
        #REPLACE_IP is private IP of this node
        server    user-prefs-server    {{ template "fullname" . }}-gov-user-prefs-service:9082

    backend app_config
        balance roundrobin
        #REPLACE_IP is private IP of this node
        server    app-config-server    {{ template "fullname" . }}-gov-app-config-service:9083

    backend catalog-http
        balance roundrobin
        #REPLACE_IP is private IP of this node
        server catalog-server {{ .Release.Name }}-gov-catalog-search-service:9080

