apiVersion: v1
data:
  .dockercfg: eyJuYS5jdW11bHVzcmVwby5jb20iOnsidXNlcm5hbWUiOiJ0b2tlbiIsInBhc3N3b3JkIjoiNzU5ZWI5OWY0YzVjMzg2YTgyZTEwZjgzNjk5ZjczZTciLCJlbWFpbCI6InBhcnRoYWtvbUBpbi5pYm0uY29tIiwiYXV0aCI6ImRHOXJaVzQ2TnpVNVpXSTVPV1kwWXpWak16ZzJZVGd5WlRFd1pqZ3pOams1WmpjelpUYz0ifX0= 
kind: Secret
metadata:
  name: {{ template "fullname" . }}-igc-registry-secret 
  labels:
     app: {{ template "fullname" . }}-igc-registry-secret
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}" 
type: kubernetes.io/dockercfg
