{{- include "sch.config.init" (list . "iisee.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.iisserver.name -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-iis-service
  labels:
     app: {{ template "fullname" . }}-iis-server-svc
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
    - name: iisconsole
      protocol: TCP
      port: 9443
      targetPort: 9443
    - name: dsengine
      protocol: TCP
      port: 31538
      targetPort: 31538
    - name: asbagent
      protocol: TCP
      port: 31531
      targetPort: 31531
  selector:
    app: {{ include "sch.names.appName" (list .) | quote }}
    release: {{ .Release.Name }}
    component: {{ $compName | quote }}
