{{- include "sch.config.init" (list . "iisee.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.iisserver.name -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-iisdocker
  labels:
     app: {{ template "fullname" . }}-iis-server-svc
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP 
  ports:
    - name: zookeeperclient
      protocol: TCP
      port: 52181
      targetPort: 52181
    - name: kafka
      protocol: TCP
      port: 59092
      targetPort: 59092
    - name: db2 
      protocol: TCP
      port: 50000
      targetPort: 50000 
    - name: zookeeper1 
      protocol: TCP
      port: 52888
      targetPort: 52888
    - name: zookeeper2 
      protocol: TCP
      port: 53888
      targetPort: 53888 
    - name: solr 
      protocol: TCP
      port: 58983
      targetPort: 58983 
  selector:
    app: {{ include "sch.names.appName" (list .) | quote }}
    release: {{ .Release.Name }}
    component: {{ $compName | quote }}
