apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-iis-server
  labels:
     app: {{ template "fullname" . }}-iis-server
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}" 
data:
  ug-setup.sh: |
    #!/bin/sh
    if ! ( pgrep dsrpc >/dev/null ); then
    source /opt/IBM/InformationServer/Server/DSEngine/dsenv
    /opt/IBM/InformationServer/Server/DSEngine/bin/uv -admin -stop
    /opt/IBM/InformationServer/Server/DSEngine/bin/uv -admin  -start
    fi
    while !(pgrep dsrpc &&  pgrep Agent)
    do
    sleep 2
    done
    
    /opt/IBM/InformationServer/shared-open-source/bin/stop-linux-services.sh
    /opt/IBM/InformationServer/shared-open-source/bin/start-linux-services.sh

    set -x #echo on
    basedir=$(dirname `which $0`)


    IIS_HOME=/opt/IBM/InformationServer
    ASBNODE_HOME=${IIS_HOME}/ASBNode
    ASBSERVER_HOME=${IIS_HOME}/ASBServer
    IS_SERVER=iisdocker
    IS_PORT=9443
    IS_ADMIN=isadmin
    IS_ADMIN_PSW=P455w0rd
    misName=${IS_SERVER}
    scriptDir=${basedir}
    DSADM=dsadm
    DSADM_PSW=P455w0rd
    IAUSER=iauser
    IAUSER_PSW=P455w0rd


    #Prerequisite user config steps
    ${ASBNODE_HOME}/bin/DirectoryCommand.sh -user ${IS_ADMIN} -password ${IS_ADMIN_PSW} -url https://${IS_SERVER}:${IS_PORT} -datastage_server ${IS_SERVER}  -set_default_ds_credentials ${DSADM}~${DSADM_PSW}
    ${ASBNODE_HOME}/bin/DirectoryCommand.sh -user ${IS_ADMIN} -password ${IS_ADMIN_PSW} -url https://${IS_SERVER}:${IS_PORT}  -assign_user_roles ${IS_ADMIN}'$'SorcererAdmin~SorcererUser~SorcererDataAdmin~RulesUser~RulesAuthor~RulesAdministrator~RulesManager

    #Prerequisite IA config for analysis database (IADB)
    sed -i "s/@IAUSER@/${IAUSER}/g" ${scriptDir}/iadb-db2-connector-imam-import-params.xml
    sed -i "s/@IAUSER_PSW@/${IAUSER_PSW}/g" ${scriptDir}/iadb-db2-connector-imam-import-params.xml
    sed -i "s/@IADB_HOST@/${misName}/g" ${scriptDir}/iadb-db2-connector-imam-import-params.xml

    ${ASBNODE_HOME}/bin/imam.sh --username ${IS_ADMIN} --password ${IS_ADMIN_PSW} --server ${IS_SERVER} --port ${IS_PORT} --importArea iadb --misName ${misName} --paramsFile ${scriptDir}/iadb-db2-connector-imam-import-params.xml --action import
    ${ASBNODE_HOME}/bin/IAAdmin.sh -user ${IS_ADMIN} -password ${IS_ADMIN_PSW} -url https://${IS_SERVER}:${IS_PORT} -setIADBParams -iaDBHost ${IS_SERVER} -iaDBDataConnection IADB -iaDataSource jdbc/IADB

    #Prerequisite UG config
    ${ASBSERVER_HOME}/bin/iisAdmin.sh -set -key com.ibm.iis.ug11_7.autoclassification.enabled -value true
    ${ASBSERVER_HOME}/bin/iisAdmin.sh -set -key com.ibm.iis.ug11_7.autoclassification.dopublish -value true
    ${ASBSERVER_HOME}/bin/iisAdmin.sh -s -k com.ibm.iis.ia.server.jobs.results.bridge -val odf
    ${ASBSERVER_HOME}/bin/iisAdmin.sh -set -key com.ibm.iis.ug.11_7_da_datasets_index_schema -value true
    ${ASBSERVER_HOME}/bin/iisAdmin.sh -s -k "com.ibm.iis.odf.autoclassification.configuration" -val "CA,TM,DQ"
    ${ASBNODE_HOME}/bin/IAAdmin.sh -user ${IS_ADMIN} -password ${IS_ADMIN_PSW} -url https://${IS_SERVER}:${IS_PORT} -create -projectContent ${scriptDir}/UGDefaultWorkspace.xml

    #Additional Config
    echo "{" > /opt/enableActionableRule.json
    echo '"useAutomaticConfiguration":true' >> /opt/enableActionableRule.json
    echo "}" >> /opt/enableActionableRule.json
    cd /opt/IBM/InformationServer/ASBNode/bin
    ./IAAdmin.sh  -user ${IS_ADMIN} -password ${IS_ADMIN_PSW}  -url https://localhost:9443 -setDataQualityConfig -content /opt/enableActionableRule.json

    #Actionable Rules
    curl -k -u isadmin:P455w0rd -H "Content-Type: application/json" -X POST -d '{"useAutomaticConfiguration":true}' https://${IS_SERVER}:${IS_PORT}/ibm/iis/ia/api/configuration/project/UGDefaultWorkspace/dataQuality
    curl -k -u isadmin:P455w0rd -H "Content-Type: application/json" -X POST -d '{"useAutomaticConfiguration":true}' https://${IS_SERVER}:${IS_PORT}/ibm/iis/ia/api/configuration/dataQuality

    #Adding service starts
    service ODFEngine stop
    service ODFEngine start
  iadb-db2-connector-imam-import-params.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <ImportParameters bridgeDisplayName="IBM InfoSphere DB2 Connector" bridgeId="CAS/DB2Connector__9.1" bridgeVersion="9.1_1.0" release="11.7.0.0">
      <CompositeParameter isRequired="true" displayName="Data connection" id="DataConnection" type="DATA_CONNECTION">
        <Parameter isRequired="true" displayName="Name" id="dcName_">
          <value>IADB</value>
        </Parameter>
        <Parameter displayName="Description" id="dcDescription_">
          <value>Information Analyzer Analysis Database</value>
        </Parameter>
        <Parameter isRequired="true" displayName="Database" id="Database">
          <value>IADB</value>
        </Parameter>
        <Parameter displayName="Instance" id="Instance">
          <value>db2inst1</value>
        </Parameter>
        <Parameter displayName="Username" id="Username">
          <value>iauser</value>
        </Parameter>
        <!-- IMPORTANT: Specify a value for the password here, or by using command-line arguments. -->
        <Parameter displayName="Password" id="Password">
          <value>P455w0rd</value>
        </Parameter>
      </CompositeParameter>
      <Parameter displayName="Include tables" id="includeTables" type="BOOLEAN">
        <value>False</value>
      </Parameter>
      <Parameter displayName="Include views" id="includeViews" type="BOOLEAN">
        <value>False</value>
      </Parameter>
      <Parameter displayName="Include nicknames" id="includeNicknames" type="BOOLEAN">
        <value>False</value>
      </Parameter>
      <Parameter displayName="Include aliases" id="includeAliases" type="BOOLEAN">
        <value>False</value>
      </Parameter>
      <Parameter displayName="XML columns as LOBs" id="importXmlAsLob" type="BOOLEAN">
        <value>False</value>
      </Parameter>
      <Parameter displayName="Include system objects" id="IncludeSystemObjects" type="BOOLEAN">
        <value>False</value>
      </Parameter>
      <Parameter displayName="Schema name filter" id="SchemaNameFilter">
        <value></value>
      </Parameter>
      <Parameter displayName="Table name filter" id="TableNameFilter">
        <value></value>
      </Parameter>
      <Parameter displayName="Assets to import" id="AssetsToImport">
        <value></value>
      </Parameter>
      <Parameter displayName="Ignore table access&#xa;errors" id="IgnoreTableAccessErrors" type="BOOLEAN">
        <value>False</value>
      </Parameter>
      <Parameter isRequired="true" displayName="Host system name" id="AP_Host system name">
        <value>iisdocker</value>
      </Parameter>
      <Parameter displayName="Database name" id="AP_Database name">
        <value>IADB</value>
      </Parameter>
    </ImportParameters>
  UGDefaultWorkspace.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <iaapi:Project xmlns:iaapi="http://www.ibm.com/investigate/api/iaapi" name="UGDefaultWorkspace">
      <description>UG Demo Workspace</description>
     </iaapi:Project>



 
