apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sidecar
  labels:
     app: {{ template "fullname" . }}-sidecar
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}" 
data:
  logstash.conf: |-
    input {
      file {
        codec => multiline {
          pattern => "^\s"
          what => "previous"
        }
        type => "app"
        path => "/opt/ibm/wlp/output/shop4InfoServer/logs/event-consumer/shop4info.log"
        start_position => "end"
      }
      file {
        codec => multiline {
          pattern => "^\s"
          what => "previous"
        }
        type => "app"
        path => "/opt/ibm/wlp/output/shop4InfoServer/logs/event-consumer/error.log"
        start_position => "end"
      }
      file {
        codec => multiline {
          pattern => "^\s"
          what => "previous"
        }
        type => "app"
        path => "/opt/ibm/wlp/output/shop4InfoServer/logs/event-consumer/scheduler.log"
        start_position => "end"
      }
      file {
        codec => multiline {
          pattern => "^\s"
          what => "previous"
        }
        type => "app"
        path => "/opt/ibm/wlp/output/shop4InfoServer/logs/event-consumer/startup.log"
        start_position => "end"
      }
      file {
        codec => multiline {
          pattern => "^\s"
          what => "previous"
        }
        type => "app"
        path => "/opt/ibm/wlp/output/shop4InfoServer/logs/shop4info-rest/error.log"
        start_position => "end"
      }
      file {
        codec => multiline {
          pattern => "^\s"
          what => "previous"
        }
        type => "app"
        path => "/opt/ibm/wlp/output/shop4InfoServer/logs/shop4info-rest/scheduler.log"
        start_position => "end"
      }
      file {
        codec => multiline {
          pattern => "^\s"
          what => "previous"
        }
        type => "app"
        path => "/opt/ibm/wlp/output/shop4InfoServer/logs/shop4info-rest/shop4info.log"
        start_position => "end"
      }
      file {
        codec => multiline {
          pattern => "^\s"
          what => "previous"
        }
        type => "app"
        path => "/opt/ibm/wlp/output/shop4InfoServer/logs/shop4info-rest/startup.log"
        start_position => "end"
      }
    }
    
    output {
      elasticsearch {
        hosts => ["{{ .Release.Name }}-{{ .Chart.Name }}-tpr-elasticsearch:9200"]
        user => "elastic"
        password => "changeme"
      }
    }
  logstash.yml: |-
     http.host: "0.0.0.0"
     path.config: /usr/share/logstash/pipeline
     xpack.monitoring.elasticsearch.url: http://{{ .Release.Name }}-{{ .Chart.Name }}-tpr-elasticsearch:9200
     xpack.monitoring.elasticsearch.username: logstash_system
     xpack.monitoring.elasticsearch.password: changeme
