{{ if and .Values.global.persistence.enabled (not .Values.shop4infoSolr.volumeClaim.existingClaimName) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.iisService.volumeClaim.name }} 
  labels:
    app: {{ template "fullname" . }}-iis-server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
   {{- if .Values.global.persistence.useDynamicProvisioning }}
  ## if present, use the storageClassName from the values.yaml, else use the
  ## default storageClass setup by kube Administrator
  ##
  ## setting storageClassName to nil means use the default storage class
  storageClassName: {{ default nil .Values.iisService.volumeClaim.storageClassName | quote }}
  {{- else }}
  ## disable dynamic provisioning
  storageClassName: ""
  {{- end }} 
  accessModes:
    - {{ .Values.iisService.volumeClaim.accessMode }}
  resources:
    requests:
      storage: {{ .Values.iisService.volumeClaim.size }} 
  {{- if (not .Values.global.persistence.useDynamicProvisioning ) }}
  selector:
    matchLabels:
      assign-to: "{{ .Release.Name }}-iiscert"
  {{- end }}
{{- end }}

