{{- include "sch.config.init" (list . "iisee.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.s4iserver.name -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
spec:
  selector:
    matchLabels:
     release: "{{ .Release.Name }}"
     component: "{{ $compName }}"
     app: {{ include "sch.names.appName" (list .) | quote }}
  replicas: 1
  template:
    metadata:
      labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 8 }}
      annotations:
{{- include "sch.metadata.annotations.metering" (list . .sch.chart.metering) | indent 8 }}
    spec:
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      hostname: shop4info-server
      initContainers:
      - name: install
        image: busybox
        command: ['sh', '-c', 'while [ ! -f /tmp/jwtkey.cer ]; do sleep 2; done;']
        volumeMounts:
        - name: secrets-pv-volume
          mountPath: /tmp
      containers:
        - name: shop4info-server
          image: {{ .Values.release.image.repository }}/iisee-eval-shop4info-server:{{ .Values.release.image.tag }}
          imagePullPolicy: {{ .Values.release.image.pullPolicy }}
          resources:
            requests:
               memory: "{{ .Values.ugResources.requests.memory }}"
               cpu: "{{ .Values.ugResources.requests.cpu }}"
          command: ['/bin/bash', '-c', '--']
          args: ["cp /jvm.options /config/jvm.options; /docker-entrypoint.sh /opt/ibm/docker/docker-server
      run shop4InfoServer;"] 
          ports:
            - containerPort: 9080
            - containerPort: 9443
          env:
            - name: SHOP4INFO_CASSANDRA_HOST
              value: {{ .Release.Name }}-cassandra
            - name: SHOP4INFO_SOLR_ZOOKEEPER_CONNECT
              value: {{ .Release.Name }}-zookeeper:2181/{{ .Release.Name }}-shop4info-solr
            - name: SHOP4INFO_KAFKA_ZOOKEEPER_CONNECT
              value: {{ .Release.Name }}-iisdocker:52181
            - name: SHOP4INFO_KAFKA_CONNECT
              value: {{ .Release.Name }}-iisdocker:59092
          volumeMounts:
            - name: config-properties
              mountPath: /config/conf/templates
            - name: config-properties
              mountPath: /config/conf/log4j2.xml
              subPath: log4j2.xml
            - name: config-properties
              mountPath: /config/conf/search/search.properties
              subPath: search.properties
            - name: config-properties
              mountPath: /config/conf/scheduler.properties
              subPath: scheduler.properties
            - name: config-properties
              mountPath: /config/conf/event-consumer.properties
              subPath: event-consumer.properties
            - name: secrets-pv-volume
              mountPath: /config/secrets
              #readOnly: true
            - name: shop4info-log
              mountPath: /opt/ibm/wlp/output/shop4InfoServer/logs
            - name: config-properties
              mountPath: /jvm.options
              subPath: jvm.options
          readinessProbe:
            httpGet:
              path: /shop4info/v1/health
              port: 9080
            periodSeconds: 60
            initialDelaySeconds: 120
            timeoutSeconds: 30
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /shop4info/v1/health
              port: 9080
            periodSeconds: 60
            initialDelaySeconds: 480
            timeoutSeconds: 30
            failureThreshold: 3
        - name: logstashsidecar
          image: docker.elastic.co/logstash/logstash:5.5.2
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: sidecarconfig
              mountPath: /opt/logstash/pipeline/logstash.conf
              subPath: logstash.conf
            - name: sidecarconfig
              mountPath: /opt/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: shop4info-log
              mountPath: /opt/ibm/wlp/output/shop4InfoServer/logs 
      volumes:
        - name: config-properties
          configMap:
            name: {{ .Release.Name }}-s4is-config
        - name: secrets-pv-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Values.iisService.volumeClaim.name }} 
        - name: shop4info-log
          emptyDir: {}
        - name: sidecarconfig
          configMap:
            name: {{ .Release.Name }}-sidecar
 
