{{- include "sch.config.init" (list . "iisee.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.s4isolr.name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-shop4info-solr
  labels:
     app: {{ template "fullname" . }}-shop4info-solr
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}"

spec:
  type: NodePort
  selector:
    app: {{ include "sch.names.appName" (list .) | quote }}
    release: {{ .Release.Name }}
    component: {{ $compName | quote }}
  ports:
    - protocol: TCP
      port: 8983
      targetPort: 8983
