{{- include "sch.config.init" (list . "iisee.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.s4isolr.name -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
spec:
  selector:
    matchLabels:
     release: "{{ .Release.Name }}"
     component: "{{ $compName }}"
     app: {{ include "sch.names.appName" (list .) | quote }}
  replicas: 1
  template:
    metadata:
      labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 8 }}
      annotations:
{{- include "sch.metadata.annotations.metering" (list . .sch.chart.metering) | indent 8 }}
    spec:
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      containers:
        - name: shop4info-solr
          image: {{ .Values.release.image.repository }}/iisee-eval-shop4info-solr:{{ .Values.release.image.tag }}
          imagePullPolicy: {{ .Values.release.image.pullPolicy }}
          resources:
            requests:
               memory: "{{ .Values.solrResources.requests.memory }}"
               cpu: "{{ .Values.solrResources.requests.cpu }}" 
          ports:
            - containerPort: 8983
          env:
            - name: SOLR_ZOOKEEPER_CONNECT
              value: {{ .Release.Name }}-zookeeper:2181/{{ .Release.Name }}-shop4info-solr
            - name: SOLR_ADVERTISED_HOST
              value: {{ .Release.Name }}-shop4info-solr
          volumeMounts:
            - mountPath: /opt/solr/server/solr
              name: solr-pv-volume
            - name: config-volume
              mountPath: /shop4info-solr/solr.xml
              subPath: solr.xml
            - name: config-volume
              mountPath: /opt/solr/server/resources/log4j.properties
              subPath: log4j.properties
          livenessProbe:
            tcpSocket:
              port: 8983
            initialDelaySeconds: 120
          readinessProbe:
            tcpSocket:
              port: 8983
            initialDelaySeconds: 60
      volumes:
        - name: solr-pv-volume
          persistentVolumeClaim:
           {{- if .Values.shop4infoSolr.volumeClaim.existingClaimName }}
            claimName: {{ .Values.shop4infoSolr.volumeClaim.existingClaimName }}
           {{- else }} 
            claimName: {{ .Release.Name }}-{{ .Values.shop4infoSolr.volumeClaim.name }} 
           {{- end }} 
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-solr
