{{- include "sch.config.init" (list . "iisee.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.s4idemoapp.name -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
spec:
  selector:
    matchLabels:
     release: "{{ .Release.Name }}"
     component: "{{ $compName }}"
     app: {{ include "sch.names.appName" (list .) | quote }}
  replicas: 1
  template:
    metadata:
      labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 8 }}
      annotations:
{{- include "sch.metadata.annotations.metering" (list . .sch.chart.metering) | indent 8 }}
    spec:
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      containers:
        - name: shop4info-demoapp
          image: {{ .Values.release.image.repository }}/iisee-eval-shop4info-demoapp:{{ .Values.release.image.tag }}
          imagePullPolicy: {{ .Values.release.image.pullPolicy }}
          resources:
            requests:
               memory: "{{ .Values.ugResources.requests.memory }}"
               cpu: "{{ .Values.ugResources.requests.cpu }}" 
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: TOKEN_SERVICE_URL
              value: https://{{ .Release.Name }}-iis-service:9443/ibm/iis/api/auth_token
            - name: SHOP4INFO_SERVICE_URL
              value: http://{{ template "fullname" . }}-shop4info-server:9080/shop4info
            - name: SOCIAL_SERVICE_URL
              value: http://{{ template "fullname" . }}-gov-social-service:9080/ibm/iis/api/social
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 20
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
