{{- include "sch.config.init" (list . "iisee.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.socialkgbridge.name -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
spec:
  selector:
    matchLabels:
     release: "{{ .Release.Name }}"
     component: "{{ $compName }}"
     app: {{ include "sch.names.appName" (list .) | quote }}
  replicas: 1
  template:
    metadata:
      labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 8 }}
      annotations:
{{- include "sch.metadata.annotations.metering" (list . .sch.chart.metering) | indent 8 }}
    spec:
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      containers:
      - name: gov-social-kg-bridge
        image: {{ .Values.release.image.repository }}/iisee-eval-gov-social-kg-bridge:{{ .Values.release.image.tag }}
        imagePullPolicy: {{ .Values.release.image.pullPolicy }}
        resources:
            requests:
               memory: "{{ .Values.ugResources.requests.memory }}"
               cpu: "{{ .Values.ugResources.requests.cpu }}"
        env:
        - name: SOCIAL_KG_BRIDGE_KG_BOOTSTRAP_SERVERS
          value: {{ .Release.Name }}-iisdocker:59092
        - name: SOCIAL_KG_BRIDGE_SOCIAL_BOOTSTRAP_SERVERS
          value: {{ .Release.Name }}-shop4info-kafka:9092
