{{ if and .Values.global.persistence.enabled (not .Values.shop4infoSolr.volumeClaim.existingClaimName) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.shop4infoSolr.volumeClaim.name }}
  labels:
    app: {{ template "fullname" . }}-shop4info-solr
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.global.persistence.useDynamicProvisioning }}
  ## if present, use the storageClassName from the values.yaml, else use the
  ## default storageClass setup by kube Administrator
  ##
  ## setting storageClassName to nil means use the default storage class
  storageClassName: {{ default nil .Values.shop4infoSolr.volumeClaim.storageClassName | quote }}
  {{- else }}
  ## disable dynamic provisioning
  storageClassName: ""
  {{- end }} 
  accessModes:
    - {{ .Values.shop4infoSolr.volumeClaim.accessMode }}
  resources:
    requests:
      storage: {{ .Values.shop4infoSolr.volumeClaim.size }}
  {{- if (not .Values.global.persistence.useDynamicProvisioning ) }}
  selector:
    matchLabels:
      assign-to: "{{ .Release.Name }}-solr"
  {{- end }}
{{- end }}
