{{- include "sch.config.init" (list . "iisee.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.userprefservice.name -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
spec:
  selector:
    matchLabels:
     release: "{{ .Release.Name }}"
     component: "{{ $compName }}"
     app: {{ include "sch.names.appName" (list .) | quote }}
  replicas: 1
  template:
    metadata:
      labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 8 }}
      annotations:
{{- include "sch.metadata.annotations.metering" (list . .sch.chart.metering) | indent 8 }}
    spec:
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      initContainers:
      - name: install
        image: busybox
        command: ['sh', '-c', 'while [ ! -f /tmp/jwtkey.cer ]; do sleep 2; done;']
        volumeMounts:
        - name: secrets-pv-volume
          mountPath: /tmp
      containers:
      - name: gov-user-prefs-service
        image: {{ .Values.release.image.repository }}/iisee-eval-gov-user-prefs-service:{{ .Values.release.image.tag }}
        imagePullPolicy: {{ .Values.release.image.pullPolicy }}
        resources:
            requests:
               memory: "{{ .Values.ugResources.requests.memory }}"
               cpu: "{{ .Values.ugResources.requests.cpu }}"
        env:
        - name: USER_PREFS_DB_TYPE
          value: db2
        - name: USER_PREFS_DB_HOST
          value: {{ .Release.Name }}-iisdocker
        - name: USER_PREFS_DB_PORT
          value: "50000"
        - name: USER_PREFS_DB_USER
          value: xmeta
        - name: USER_PREFS_DB_PASSWORD
          value: P455w0rd
        - name: USER_PREFS_DB_NAME
          value: xmeta
        ports:
        - containerPort: 9082
        volumeMounts:
        - name: secrets-pv-volume
          mountPath: /config/secrets
        readinessProbe:
          httpGet:
            path: /ibm/iis/api/user_prefs/v1
            port: 9082
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /ibm/iis/api/user_prefs/v1/health
            port: 9082
          initialDelaySeconds: 120
      volumes:
      - name: secrets-pv-volume
        persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Values.iisService.volumeClaim.name }}  
