###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
{{- include "sch.config.init" (list . "sch.chart.config.values") }}
{{- $compName :=  .sch.chart.components.common.secretGeneratorName }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
  annotations:
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 8 }}
      annotations:
{{- include "sch.metadata.annotations.metering" (list . .sch.chart.metering) | indent 8 }}
    spec:
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      restartPolicy: Never
      containers:
      - name: {{ $compName | quote }}
        image: ibmcom/mb-tools:2.0.0
        volumeMounts:
        - name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
          mountPath: /mbfiles/gen-keystore.sh
          subPath: gen-keystore.sh
      volumes:
      - name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
        configMap:
          name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
          defaultMode: 0744
