###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
{{- include "sch.config.init" (list . "sch.chart.config.values") }}
{{- $compName :=  .sch.chart.components.common.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
data:
  providerUsername: {{ .Values.broker.provider.user | b64enc | quote }}
  providerPassword: {{ required ".Values.broker.provider.password" .Values.broker.provider.password | b64enc | quote }}
  brokerUsername: {{ .Values.broker.user | b64enc | quote }}
  brokerPassword: {{ required ".Values.broker.password" .Values.broker.password | b64enc | quote }}
  cloudsmUsername: {{ .Values.cloudsm.user | b64enc | quote }}
  cloudsmPassword: {{ required ".Values.cloudsm.password" .Values.cloudsm.password | b64enc | quote }}
  iamClientId: {{ .Values.iam.clientId | b64enc | quote }}
  iamClientSecret: {{ .Values.iam.clientSecret | b64enc | quote }}
