apiVersion: v1
description: IBM Db2 Event Store Developer Edition, which is powered by DSX technology, brings together the power of Spark, Data Science tooling such as Jupyter Notebooks with Scala and Python and allows to perform high ingest rate and real time analytics on your data.
home: https://www.ibm.com/us-en/marketplace/db2-event-store
icon: https://raw.githubusercontent.com/IBMProjectEventStore/EventStore-DeveloperEdition/master/icon.ico
keywords:
  - Data Science
  - Spark
  - Python
  - Scala
  - notebooks
  - EventStore
  - Event Store
  - amd64
  - Tech
  - ICP
maintainers:
  - name: IBM Analytics
name: ibm-eventstore-dev
tillerVersion: '>=2.7.2'
version: 1.0.2
appVersion: 1.1.5
