address:
  virtualIp: ""
  eventstoreNode: ""
disk:
  storagePath: "/ibm"
  computePath: "/ibm"

ibmEsPvc:
  persistence:
    existingClaimName: "ibm-es-pvc"
    size: "100Gi"
    storageClassName: "glusterfs-distributed"

ibm-dsx-dev:
  image:
    pullPolicy: "IfNotPresent"
  persistence:
    useDynamicProvisioning: true
  userHomePvc:
    persistence:
      existingClaimName: ""
      size: "10Gi"
      storageClassName: "glusterfs-distributed"
  sparkMetricsPvc:
    persistence:
      storageClassName: "glusterfs-distributed"
      existingClaimName: ""
      size: "50Gi"
