address:
  __metadata:
    label: "Address Space Settings"
  virtualIp:
    __metadata:
      label: "Name of the proxy node"
      description: "The Proxy node name of the cluster (https://<Cluster IP>:8443/console/platform/nodes)"
      type: "string"
      required: true
  eventstoreNode:
    __metadata:
      label: "Name of the IBM Db2 Event Store worker node"
      description: "The Worker node name which satisfies Event Store hardware requirements (https://<Cluster IP>:8443/console/platform/nodes)"
      type: "string"
      required: true
disk:
  __metadata:
    label: "Disk Space Settings"
  storagePath:
    __metadata:
      label: "IBM Db2 Event Store Local storage Path"
      description: "Directory where the Db2 Event Store local logs will be stored. If the directory doesn't exist, it will be automatically created. If it does, a new 'eventstore' directory will be created within. Example: /path/to/my/dir"
      type: "string"
      required: true
  computePath:
    __metadata:
      label: "IBM Db2 Event Store Local metadata Path"
      description: "Directory where the Db2 Event Store metadata will be stored. If the directory doesn't exist, it will be automatically created. If it does, a new 'eventstore' directory will be created within. This directory can be the same as the storage path. Example: /path/to/my/dir"
      type: "string"
      required: true
ibmEsPvc:
  __metadata:
    label: "IBM Db2 Event Store Persistent Volume Claim Settings"
  persistence:
    existingClaimName:
      __metadata:
        label: "Claim Name"
        description: "Specify the name of the persistent volume claim to use for Event Store pod. If you do not use the provided default name, you must create a claim before you deploy the chart."
        type: "string"
        required: true
    storageClassName:
      __metadata:
        label: "Storage Class Name"
        description: "Choose a specific storage class name."
        type: "string"
        required: false
    size:
      __metadata:
        label: "Size"
        description: "Size of the Persistent Volume. Memory is measured in bytes. You can express memory as a plain integer or as a fixed-point integer using one of these suffixes: E, P, T, G, M, K. You can also use the power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki."
        type: "string"
        required: true
ibm-dsx-dev:
  __metadata:
    label: "Jupyter Notebook Persistent Volume Claim Settings"
  image:
    pullPolicy:
      __metadata:
        label: "Docker image pull policy"
        description: "Always, Never, or IfNotPresent. Defaults to IfNotPresent"
        type: "string"
        immutable: false
        required: true
        options:
        - label: "Always"
          value: "Always"
        - label: "Never"
          value: "Never"
        - label: "IfNotPresent"
          value: "IfNotPresent"
  persistence:
    useDynamicProvisioning:
      __metadata:
        label: "Use dynamic provisioning for persistent volume"
        description: "If dynamic provisioning is available in the cluster this option will automatically provision the requested persistent volumes if set to true. Defaults to true."
        type: "boolean"
        immutable: "true"
        required: true
  userHomePvc:
    persistence:
      existingClaimName:
        __metadata:
          label: "User Home Claim Name"
          description: "Name of an existing Persistent Volume Claim that references a Persistent Volume"
          type: "string"
          required: false
      storageClassName:
        __metadata:
          label: "User Home Storage Class Name"
          description: "Choose a specific storage class name."
          type: "string"
          required: false
      size:
        __metadata:
          label: "User Home Size"
          description: "Size of the Persistent Volume. Memory is measured in bytes. You can express memory as a plain integer or as a fixed-point integer using one of these suffixes: E, P, T, G, M, K. You can also use the power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki."
          type: "string"
          required: true
  sparkMetricsPvc:
    persistence:
      existingClaimName:
        __metadata:
          label: "Spark Metrics Claim Name"
          description: "Name of an existing Persistent Volume Claim that references a Persistent Volume"
          type: "string"
          required: false
      storageClassName:
        __metadata:
          label: "Spark Metrics Storage Class Name"
          description: "Choose a specific storage class name."
          type: "string"
          required: false
      size:
        __metadata:
          label: "Spark Metrics Size"
          description: "Size of the Persistent Volume. Memory is measured in bytes. You can express memory as a plain integer or as a fixed-point integer using one of these suffixes: E, P, T, G, M, K. You can also use the power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki."
          type: "string"
          required: true
