###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
{{- include "sch.config.init" (list . "sch.chart.config.values") }}
{{- $compName := .sch.chart.components.couchdb.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
type: Opaque
data:
  adminUsername: {{ .Values.couchdb.adminUsername | b64enc | quote }}
  adminPassword: {{ required ".Values.couchdb.adminPassword" .Values.couchdb.adminPassword | b64enc | quote }}
  cookieAuthSecret: {{ randAlphaNum 10 | b64enc | quote }}
