{{- if and .Values.alertmanager.persistentVolume.enabled (not .Values.alertmanager.persistentVolume.existingClaimName) }}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: alertmanager
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-alertmanager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.alertmanager.persistentVolume.size }}"
{{- if .Values.alertmanager.persistentVolume.useDynamicProvisioning }}
  storageClassName: {{ default nil .Values.alertmanager.persistentVolume.storageClass | quote }}
{{- else }}
  storageClassName: {{ default "" .Values.alertmanager.persistentVolume.storageClass | quote }}
{{- if .Values.alertmanager.persistentVolume.selector.label }}
  selector:
    matchExpressions:
      - {key: {{ .Values.alertmanager.persistentVolume.selector.label }}, operator: In, values: [{{ .Values.alertmanager.persistentVolume.selector.value }}]}
{{- end }}
{{- end }}
{{- end }}
