# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}-alertmanager
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: alertmanager
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-alertmanager
spec:
  ports:
    - name: web
      port: {{ .Values.alertmanager.port }}
      protocol: TCP
    {{- if or (eq .Values.mode "managed") .Values.tls.enabled }}
      targetPort: 8443
    {{- else }}
      targetPort: 9093
    {{- end }}
  selector:
    app: {{ template "prometheus.fullname" . }}-alertmanager
    component: alertmanager
    release: {{ .Release.Name }}
  type: {{ .Values.alertmanager.service.type }}
