# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: grafana
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "grafana.fullname" . }}
spec:
  ports:
    - name: "web"
      port: {{ .Values.grafana.port }}
      protocol: TCP
    {{- if or (eq .Values.mode "managed") .Values.tls.enabled }}
      targetPort: 8443
    {{- else }}
      targetPort: 3000
    {{- end }}
  selector:
    app: {{ template "grafana.fullname" . }}
    component: grafana
    release: {{ .Release.Name }}
  type: "{{ .Values.grafana.service.type }}"
