apiVersion: v1
name: prometheus
version: 0.1.0
appVersion: 0.1.0
tillerVersion: ">=2.7.2"
description: Helm chart for deploying prometheus
keywords:
  - prometheus
sources:
  - https://github.com/prometheus/prometheus
