{{- if .Values.prometheusProbe.enabled -}}
# Service.yaml required to expose the IP address of the probe for receiving notification.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus.servicename" . }}
  labels:
    app: {{ template "fullname" . }}-prometheusprobe
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: prometheusprobe
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.prometheusProbe.service.type }}
  ports:
    - port: {{ .Values.prometheusProbe.service.externalPort }}
      targetPort: 80
      protocol: TCP
      name: webhook-http
  selector:
    app: {{ template "fullname" . }}-prometheusprobe
    release: {{ .Release.Name }}
{{- end -}}