{{- if .Values.prometheusProbe.enabled -}}
{{- if .Values.prometheusProbe.ingress.enabled -}}
{{- $serviceName := include "prometheus.servicename" . -}}
{{- $servicePort := .Values.prometheusProbe.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-prometheusprobe
  labels:
    app: {{ template "fullname" . }}-prometheusprobe
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: prometheusprobe
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.prometheusProbe.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.prometheusProbe.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.prometheusProbe.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /probe/webhook/prometheus
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.prometheusProbe.ingress.tls }}
  tls:
{{ toYaml .Values.prometheusProbe.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}