
{{- if .Values.prometheusProbe.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "fullname" . }}-prometheusprobe
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: prometheusprobe
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}-prometheusprobe-config
data:
{{- include "probePrometheusConfig" . | indent 2 }}
{{- end -}}
