{{- if .Values.logstashProbe.enabled -}}
# Service.yaml required to expose the IP address of the probe for receiving notification.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "logstash.servicename" . }}
  labels:
    app: {{ template "fullname" . }}-logstashprobe
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: logstashprobe
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.logstashProbe.service.type }}
  ports:
    - port: {{ .Values.logstashProbe.service.externalPort }}
      targetPort: 80
      protocol: TCP
      name: webhook-http
  selector:
    app: {{ template "fullname" . }}-logstashprobe
    release: {{ .Release.Name }}
{{- end -}}
