{{- if .Values.prometheusProbe.enabled -}}
{{- if .Values.prometheusProbe.autoscaling.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" . }}-prometheusprobe
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}-prometheusprobe
    component: prometheusprobe
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "fullname" . }}-prometheusprobe
    apiVersion: extensions/v1beta1
  minReplicas: {{ .Values.prometheusProbe.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.prometheusProbe.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.prometheusProbe.autoscaling.cpuUtil }}
  {{- end -}}
  {{- end -}}