{{- if .Values.logstashProbe.enabled -}}
{{- if .Values.logstashProbe.autoscaling.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" . }}-logstashprobe
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}-logstashprobe
    component: logstashprobe
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "fullname" . }}-logstashprobe
    apiVersion: extensions/v1beta1
  minReplicas: {{ .Values.logstashProbe.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.logstashProbe.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.logstashProbe.autoscaling.cpuUtil }}
{{- end -}}
{{- end -}}