{{- if .Values.logstashProbe.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "fullname" . }}-logstashprobe
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: logstashprobe
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}-logstashprobe-config
data:
{{- include "probeLogstashConfig" . | indent 2 }}
{{- end -}}
