# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "elasticsearch.fullname" . }}-curator-config"
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    component: "{{ .Values.curator.name }}"
data:
  action.yml: |-
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    #
    # Also remember that all examples have 'disable_action' set to True.  If you
    # want to use this action as a template, be sure to set this to False after
    # copying it.
    actions:
      1:
        action: delete_indices
        description: "Delete user log indices that are older than {{ .Values.curator.app.count }} {{ .Values.curator.app.unit }}. Cron schedule: {{ .Values.curator.schedule }}"
        options:
          timeout_override:
          continue_if_exception: True
          ignore_empty_list: True
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: logstash-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: {{ .Values.curator.app.unit }}
          unit_count: {{ .Values.curator.app.count }}
      2:
        action: delete_indices
        description: "Delete elastic system monitoring log indices that are older than {{ .Values.curator.monitoring.count }} {{ .Values.curator.monitoring.unit }}. Cron schedule: {{ .Values.curator.schedule }}"
        options:
          timeout_override:
          continue_if_exception: True
          ignore_empty_list: True
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: .monitoring
        - filtertype: pattern
          kind: prefix
          value: .monitoring-alerts
          exclude: True
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: {{ .Values.curator.monitoring.unit }}
          unit_count: {{ .Values.curator.monitoring.count }}
      3:
        action: delete_indices
        description: "Delete elastic watcher history indices that are older than {{ .Values.curator.watcher.count }} {{ .Values.curator.watcher.unit }}. Cron schedule: {{ .Values.curator.schedule }}"
        options:
          timeout_override:
          continue_if_exception: True
          ignore_empty_list: True
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: .watcher-history
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: {{ .Values.curator.watcher.unit }}
          unit_count: {{ .Values.curator.watcher.count }}
  config.yml: |-
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
      hosts:
        - {{ .Values.elasticsearch.name }}
      port: {{ .Values.elasticsearch.client.restPort }}
      url_prefix:
{{- if .Values.security.enabled }}
      use_ssl: True
      certificate: /curator/tls/ca.crt
      client_cert: /curator/tls/curator.crt
      client_key: /curator/tls/curator.key
      ssl_no_validate: False
{{- else }}
      use_ssl: False
      ssl_no_validate: True
{{- end }}
      http_auth:
      timeout: 30
      master_only: False
    logging:
      loglevel: INFO
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
  cron: |-
    {{ .Values.curator.schedule }} /bin/sh /clean-indices.sh
    # An empty line is required at the end of this file for a valid cron file.
