# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    component: "{{ .Values.elasticsearch.master.name }}"
    release: "{{ .Release.Name }}"
    role: "master"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
  name: "{{ .Values.elasticsearch.master.name }}-discovery"
spec:
  type: ClusterIP
  selector:
    app: "{{ template "elasticsearch.fullname" . }}"
    component: "{{ .Values.elasticsearch.master.name }}"
    role: "master"
  ports:
  - name: transport
    port: {{ .Values.elasticsearch.internalPort }}
    targetPort: {{ .Values.elasticsearch.internalPort }}
    protocol: TCP
