# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    component: "{{ .Values.elasticsearch.master.name }}"
    release: "{{ .Release.Name }}"
    role: "master"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
  name: "{{ template "master.fullname" . }}"
spec:
  selector:
    matchLabels:
      app: "{{ template "elasticsearch.fullname" . }}"
      component: "{{ .Values.elasticsearch.master.name }}"
      release: "{{ .Release.Name }}"
      role: "master"
      heritage: "{{ .Release.Service }}"
  replicas: {{ .Values.elasticsearch.master.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: "{{ template "elasticsearch.fullname" . }}"
        component: "{{ .Values.elasticsearch.master.name }}"
        role: "master"
        release: "{{ .Release.Name }}"
        chart: "{{ .Chart.Name }}"
        heritage: "{{ .Release.Service }}"
      annotations:
        productName: Elasticsearch
        productVersion: 5.5.1
        productID: none
    spec:
{{ include "elasticsearch.nodeaffinity" . | indent 6 }}
    {{- if eq .Values.elasticsearch.master.antiAffinity "hard" }}
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app: "{{ template "elasticsearch.fullname" . }}"
                component: "{{ .Values.elasticsearch.master.name }}"
                release: "{{ .Release.Name }}"
                role: "master"
                heritage: "{{ .Release.Service }}"
    {{- else if eq .Values.elasticsearch.master.antiAffinity "soft" }}
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: "{{ template "elasticsearch.fullname" . }}"
                component: "{{ .Values.elasticsearch.master.name }}"
                release: "{{ .Release.Name }}"
                role: "master"
                heritage: "{{ .Release.Service }}"
    {{- end }}
      initContainers:
      - name: "sysctl"
        image: "{{ .Values.elasticsearch.initImage.repository }}:{{ .Values.elasticsearch.initImage.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command: ["/bin/sh", "-c", "sysctl -w vm.max_map_count=262144 && sed -i '/^vm.max_map_count /d' /etc/sysctl.conf && echo 'vm.max_map_count = 262144' >> /etc/sysctl.conf"]
        securityContext:
          privileged: true
{{- if and .Values.security.enabled (eq .Values.security.provider "searchguard-tls") }}
      - name: plugin-bundle
        image: {{ .Values.elasticsearch.pluginImage.repository }}:{{ .Values.elasticsearch.pluginImage.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: plugin-bundle
          mountPath: /usr/share/elasticsearch/plugin-bundles
{{- end }}
      containers:
      - name: es-master
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
        image: {{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/bash", "/scripts/entrypoint.sh"]
        resources:
          limits:
            memory: {{ .Values.elasticsearch.master.memoryLimit }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.elasticsearch.internalPort }}
          initialDelaySeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.elasticsearch.internalPort }}
          periodSeconds: 30
        env:
        - name: "ES_JAVA_OPTS"
          value: "-Xms{{ .Values.elasticsearch.master.heapSize }} -Xmx{{ .Values.elasticsearch.master.heapSize }}"
        - name: CFG_BASEDIR
          value: /usr/share/elasticsearch
{{- if .Values.security.enabled }}
        - name: CA_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "elasticsearch.fullname" . }}-pki-secret
              key: caTruststorePassword
        - name: APP_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "elasticsearch.fullname" . }}-pki-secret
              key: appKeystorePassword
{{- end }}
        ports:
        - containerPort: {{ .Values.elasticsearch.internalPort }}
          name: transport
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: config-x86
          mountPath: /usr/share/elasticsearch-config-x86/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: config-ppc
          mountPath: /usr/share/elasticsearch-config-ppc/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: entrypoint
          mountPath: /scripts
{{- if .Values.security.enabled }}
  {{- if eq .Values.security.provider "xpack" }}
        - name: config-xpack
          mountPath: /usr/share/elasticsearch/config/x-pack
  {{- end }}
        - name: certs
          mountPath: "/usr/share/elasticsearch/config/tls"
          readOnly: true
{{- end }}
        - name: plugin-bundle
          mountPath: /usr/share/elasticsearch/plugin-bundles
      volumes:
          - emptyDir:
              medium: ""
            name: data
          - emptyDir:
              medium: ""
            name: plugin-bundle
          - name: config-x86
            configMap:
              name: {{ template "elasticsearch.fullname" . }}-config
              items:
                - key: master.yml-x86
                  path: elasticsearch.yml
          - name: config-ppc
            configMap:
              name: {{ template "elasticsearch.fullname" . }}-config
              items:
                - key: master.yml-ppc
                  path: elasticsearch.yml
{{- if and .Values.security.enabled (eq .Values.security.provider "xpack") }}
          - name: config-xpack
            configMap:
              name: {{ template "elasticsearch.fullname" . }}-config
              items:
                - key: roles.yml
                  path: roles.yml
                - key: role_mapping.yml
                  path: role_mapping.yml
{{- end }}
          - name: entrypoint
            configMap:
              name: {{ template "elasticsearch.fullname" . }}-entrypoint
              defaultMode: 365
              items:
                - key: entrypoint.sh
                  path: entrypoint.sh
                - key: install-plugin.sh
                  path: install-plugin.sh
                - key: map-config.sh
                  path: map-config.sh
{{- if .Values.security.enabled }}
          - name: certs
            secret:
              secretName: {{ template "fullname" . }}-certs
{{- end }}
