{{- if .Values.security.enabled }}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "pki-init"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: "{{ template "elasticsearch.fullname" . }}-pki-init-binding"
  annotations:
    "helm.sh/hook": pre-install, post-delete
    "helm.sh/hook-weight": "-18"
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
subjects:
- kind: Group
  name: system:serviceaccounts:{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ template "elasticsearch.fullname" . }}-pki-init
  apiGroup: rbac.authorization.k8s.io
{{- end }}
