{{- if .Values.security.enabled }}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "elasticsearch.fullname" . }}-pki-secret"
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "pki-secret"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  caKeystorePassword: "{{ .Values.security.ca.keystore.password | b64enc }}"
  caTruststorePassword: "{{ .Values.security.ca.truststore.password | b64enc }}"
  appKeystorePassword: "{{ .Values.security.app.keystore.password | b64enc }}"
{{- end }}
