{{- if and .Values.security.enabled (eq .Values.security.provider "searchguard-tls") }}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "elasticsearch.fullname" . }}-searchguard-config"
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "elastic-searchguard-config"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
data:
  sg_config.yml: |-
{{ .Files.Get "searchguard/sg_config.yml" | indent 4 }}
  sg_action_groups.yml: |-
{{ .Files.Get "searchguard/sg_action_groups.yml" | indent 4 }}
  sg_internal_users.yml: |-
{{ .Files.Get "searchguard/sg_internal_users.yml" | indent 4 }}
  sg_roles.yml: |-
{{ .Files.Get "searchguard/sg_roles.yml" | indent 4 }}
  sg_roles_mapping.yml: |-
{{ .Files.Get "searchguard/sg_roles_mapping.yml" | indent 4 }}
{{- end }}
