# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.filebeat.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    role: "filebeat"
  name: "{{ template "filebeat.fullname" . }}"
spec:
  selector:
    matchLabels:
      app: "{{ template "elasticsearch.fullname" . }}"
      component: "{{ .Values.filebeat.name }}"
      role: "filebeat"
      heritage: "{{ .Release.Service }}"
      release: "{{ .Release.Name }}"
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: "{{ template "elasticsearch.fullname" . }}"
        component: "{{ .Values.filebeat.name }}"
        role: "filebeat"
        chart: "{{ .Chart.Name }}"
        heritage: "{{ .Release.Service }}"
        release: "{{ .Release.Name }}"
      annotations:
        productName: filebeat
        productVersion: 5.5.1
        productID: none
    spec:
      terminationGracePeriodSeconds: 30
      {{- if .Values.filebeat.scope.nodes }}
      nodeSelector:
{{ toYaml .Values.filebeat.scope.nodes | indent 8 }}
      {{- end }}
      {{- if eq .Values.mode "managed" }}
      tolerations:
      - key: "dedicated"
        operator: "Exists"
        effect: "NoSchedule"
      {{- end }}
      securityContext:
        runAsUser: 0
      containers:
      - name: filebeat
        image: {{ .Values.filebeat.image.repository }}:{{ .Values.filebeat.image.tag }}
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "ps aux | grep '[f]ilebeat' || exit 1"
          initialDelaySeconds: 10
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "ps aux | grep '[f]ilebeat' || exit 1"
          periodSeconds: 30
        env:
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
{{- if .Values.security.enabled }}
        - name: CA_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "elasticsearch.fullname" . }}-pki-secret
              key: caTruststorePassword
        - name: APP_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "elasticsearch.fullname" . }}-pki-secret
              key: appKeystorePassword
{{- end }}
        volumeMounts:
        - name: config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
{{- if .Values.security.enabled }}
        - name: certs
          mountPath: "/usr/share/elasticsearch/config/tls"
          readOnly: true
{{- end }}
        - name: container-log
          mountPath: /var/log/containers
          readOnly: true
        - name: pod-log
          mountPath: /var/log/pods
          readOnly: true
        - name: docker-log
          mountPath: /var/lib/docker/containers/
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ template "filebeat.fullname" . }}-config
          items:
          - key: filebeat.yml
            path: filebeat.yml
{{- if .Values.security.enabled }}
      - name: certs
        secret:
          secretName: {{ template "fullname" . }}-certs
{{- end }}
      - emptyDir:
          medium: ""
        name: data
      - name: container-log
        hostPath:
          path: /var/log/containers
      - name: pod-log
        hostPath:
          path: /var/log/pods
      - name: docker-log
        hostPath:
          path: /var/lib/docker/containers
