{{- if .Values.kibana.install -}}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
  name: {{ template "kibana.fullname" . }}-init-entrypoint
data:
  entrypoint.sh: |-
    #!/bin/sh
    # if the kibana server returns a non-successful status,
    # exit the job with this exit code. A retry will be triggered by k8s
    set -uo pipefail

    # 1. prepare kibana api url
    {{- if .Values.security.enabled }}
      protocol=https
    {{ else }}
      protocol=http
    {{- end }}

    endpoint={{ .Values.kibana.name }}
    port={{ .Values.kibana.internal }}
    url="$protocol://$endpoint:$port"
    index_pattern="logstash-*"
    id="logstash-*"
    time_field="@timestamp"

    # 2. make kibana call to set index pattern
    # more api info at: https://github.com/elastic/kibana/issues/3709
    echo creating index pattern
    # curl -f to fail on error
    set -x
    curl -f -k -XPOST -H "Content-Type:application/json" -H "kbn-xsrf:anything" \
      $url/es_admin/.kibana/index-pattern/$index_pattern/_create \
      -d"{\"title\":\"logstash-*\",\"timeFieldName\":\"$time_field\"}"
    exit_code=$?
    set +x
    echo $'\n'
    date
    echo "curl returned code $exit_code"

    # 3. make kibana call to set default index
    # curl exits with code 22 for 409 error
    # kibana returns 409 when the index pattern already exists
    if [ "${exit_code}" = "0" ] || [ "${exit_code}" = "22" ]
    then
      echo setting default index
      set -x
      curl -k -XPOST -H "Content-Type: application/json" -H "kbn-xsrf: anything" \
        "$url/api/kibana/settings/defaultIndex" \
        -d"{\"value\":\"$id\"}"
      exit_code=$?
      set +x
      echo $'\n'
      date
      echo "curl returned code $exit_code"
    else
      echo "default index not set as index pattern creation failed"
    fi

    echo "job exit code $exit_code"
    exit $exit_code
{{ end }}
