{{- if .Values.kibana.install -}}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "kibana.fullname" . }}-config"
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.kibana.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
data:
  kibana.yml-x86: |-
    # x86-only config. Must include refs to X-Pack.
{{ include "kibana.config" . | indent 4 }}
{{ include "kibana.xpack" . | indent 4 }}
  kibana.yml-ppc: |-
    # ppc64le-only config. Must not include refs to X-Pack.
{{ include "kibana.config" . | indent 4 }}

{{- end }}
