# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    component: "{{ .Values.logstash.name }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
  name: "{{ .Values.logstash.name }}"
spec:
  ports:
  - name: "beats"
    port: {{ .Values.logstash.port }}
    targetPort: {{ .Values.logstash.port }}
  selector:
    app: "{{ template "elasticsearch.fullname" . }}"
    component: "{{ .Values.logstash.name }}"
    role: "logstash"
