###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
{{- include "sch.config.init" (list . "sch.chart.config.values") }}
{{- $compName :=  .sch.chart.components.cloudsmCommon.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
data:
  shared.key: {{ randAscii 16 | quote }}
  wasaas-network.properties: |-
    connection_timeout=30000
    private_ip_block={{ .Values.vsphere.ipPool }}
  cloudsm.properties: |-
    adaptors="AdaptorName\=TVMAdaptor_0001,IPAddress\={{ .Values.cam.ip }}\:{{ .Values.cam.port }},UserId\={{ .Values.cam.user }},AdaptorType\=TerraformVmWareResourceAdaptor,Password\={{ .Values.cam.password | b64enc }}"
    Environment={{ .Values.environment.name }}
    {{- if .Values.migration.enabled }}
    FileSystemMountName={{ .Values.migration.mountPoint }}
    FileSystemUrl={{ .Values.migration.serverAddress }}
    {{- end }}

  cloudsm.yaml: |-
    Environment: local
    Adaptor: TVMAdaptor_0001
    Capacity:  {{ .Values.cloudsm.capacity }}
    cloudConnectionId: {{ .Values.cam.cloudConnectionName }}
    instanceId: {{ .Values.cam.contentRuntimeName }}

    CommonVariables:
     - name: os_image
       value: {{ required ".Values.vsphere.osImage" .Values.vsphere.osImage }}
     - name: os_admin_user
       value: {{ .Values.vsphere.osAdminUser }}
     - name: os_admin_password_image
       value: {{ .Values.vsphere.osAdminPassword }}
     - name: vsphere_root_disk_size
       value: {{ .Values.vsphere.rootDiskSize }}
     - name: vsphere_root_disk_datastore
       value: {{ .Values.vsphere.rootDiskDatastore }}
     - name: vsphere_resource_pool
       value: {{ .Values.vsphere.resourcePool }}
     {{- if .Values.vsphere.folder }}
     - name: vsphere_folder
       value: {{ .Values.vsphere.folder }}
     {{- end }}
     - name: vsphere_domain
       value: {{ .Values.vsphere.domain }}
     - name: vsphere_datacenter
       value: {{ .Values.vsphere.datacenter }}
     - name: vsphere_network_interface_label
       value: {{ .Values.vsphere.networkInterfaceLabel }}
     - name: vsphere_dns_servers
       value:
     {{ toYaml .Values.vsphere.dnsServers | indent 4 }}
     - name: vsphere_dns_suffixes
       value:
     {{ toYaml .Values.vsphere.dnsSuffixes | indent 4 }}
     - name: vsphere_ipv4_gateway
       value: {{ .Values.vsphere.ipv4Gateway }}
     - name: vsphere_ipv4_prefix_length
       value: {{ .Values.vsphere.ipv4PrefixLength }}
