kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ibm-nginx
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    run: ibm-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ibm-nginx-deployment-pod
  template:
    metadata:
      labels:
        app: ibm-nginx
        component: ibm-nginx
        run: ibm-nginx-deployment-pod
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
      annotations:
        productName: {{ .Chart.Name }}
        productID: IBMDb2EventStore_111_perpetual_00000
        productVersion: {{ .Chart.Version }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                  - amd64
      terminationGracePeriodSeconds: 0
      containers:
        - name: ibm-nginx-container
          image: {{ .Values.nginxContainer.image.repository }}:{{ .Values.nginxContainer.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy | quote }}
          resources:
{{ toYaml .Values.nginxContainer.resources | indent 12 }}
          ports:
            - containerPort: 443
              protocol: TCP
          env:
          - name: NAMESPACE
            value: {{.Release.Namespace}}
          volumeMounts:
            - mountPath: /user-home
              name: user-home
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 443
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 443
            timeoutSeconds: 1
      volumes:
        - name: "user-home"
          persistentVolumeClaim:
          {{- if .Values.userHomePvc.persistence.existingClaimName }}
            claimName: {{ .Values.userHomePvc.persistence.existingClaimName }}
          {{- else }}
            claimName: {{ template "fullname" . }}-{{ .Values.userHomePvc.name }}
          {{- end }}
