apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    run: spark-worker-deployment
spec:
  selector:
    matchLabels:
      run: spark-worker-deployment-pod
  template:
    metadata:
      labels:
        app: spark
        component: spark-worker
        run: spark-worker-deployment-pod
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
      annotations:
        productName: {{ .Chart.Name }}
        productID: IBMDb2EventStore_111_perpetual_00000
        productVersion: {{ .Chart.Version }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                  - amd64
      containers:
      - name: spark-worker-container
        image: {{ .Values.sparkContainer.image.repository }}:{{ .Values.sparkContainer.image.tag }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy | quote }}
        command: ["bash"]
        args: ["-c", "umask 0 ; /start_worker"]
        resources:
{{ toYaml .Values.sparkContainer.resources | indent 12 }}
        ports:
          - containerPort: 8081
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - mountPath: /user-home
          name: user-home
      volumes:
      - name: user-home
        persistentVolumeClaim:
          {{- if .Values.userHomePvc.persistence.existingClaimName }}
            claimName: {{ .Values.userHomePvc.persistence.existingClaimName }}
          {{- else }}
            claimName: {{ template "fullname" . }}-{{ .Values.userHomePvc.name }}
          {{- end }}
