kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spawner-api
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    run: spawner-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: spawner-api-deployment-pod
  template:
    metadata:
      labels:
        app: spawner-api
        component: spawner-api
        run: spawner-api-deployment-pod
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
      annotations:
        productName: {{ .Chart.Name }}
        productID: IBMDb2EventStore_111_perpetual_00000
        productVersion: {{ .Chart.Version }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                  - amd64
      terminationGracePeriodSeconds: 0
      containers:
        - name: spawner-api-container
          image: {{ .Values.spawnerApiContainer.image.repository }}:{{ .Values.spawnerApiContainer.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy | quote }}
          resources:
{{ toYaml .Values.spawnerApiContainer.resources | indent 12 }}
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
          - name: SPAWNER_DEFS_PATH
            value: "/user-home/_global_/config/.runtime-definitions/ibm"
          - name: SPAWNER_USER_DEFS_PATH
            value: "/user-home/_global_/config/.runtime-definitions/custom"
          - name: NAMESPACE
            value: {{.Release.Namespace}}
          volumeMounts:
            - mountPath: /user-home
              name: user-home
            - mountPath: "/user-home/_global_/config/.runtime-definitions/ibm"
              name: rt-def-mount
      volumes:
        - name: "user-home"
          persistentVolumeClaim:
          {{- if .Values.userHomePvc.persistence.existingClaimName }}
            claimName: {{ .Values.userHomePvc.persistence.existingClaimName }}
          {{- else }}
            claimName: {{ template "fullname" . }}-{{ .Values.userHomePvc.name }}
          {{- end }}
        - name: rt-def-mount
          configMap:
            name: runtimes-def-configmap
