kind: Service
apiVersion: v1
metadata:
  name: spawner-api-svc
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    run: spawner-api-svc
    component: spawner-api
spec:
  type: ClusterIP
  ports:
  - name: spawner-port
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    run: spawner-api-deployment-pod
    component: spawner-api
