apiVersion: 2.0.0
description: Db2 Warehouse Developer-C for Non-Production v2.5.0
engine: gotpl
home: https://www.ibm.com/hr-en/marketplace/db2-warehouse
icon: https://www.ibm.com/support/knowledgecenter/SS6NHC/com.ibm.swg.im.dashdb.kc.doc/images/dashDB_64.png
keywords:
- dashdb
- db2warehouse
- warehouse
- local
- db2
- database
- sql
maintainers:
- name: IBM Analytics
name: ibm-db2warehouse-dev
sources:
- https://github.com/IBM/charts/tree/master/stable
tillerVersion: '>=2.4.0'
version: 2.0.0
