arch:
  __metadata:
    name: "Architecture"
    label: "Worker node architecture"
    description: "Select the architecture for the IBM Db2 Warehouse image"
    type: "string"
    immutable: "false"
    required: true
    options:
      - label: "AMD64 platforms"
        value: "x86"
      - label: "Power 64 LE platforms"
        value: "ppcle"
      - label: "zLinux platforms"
        value: "s390x"

BLUADMPASS:
  __metadata:
    label: "BLUADMPASS"
  password:
    __metadata:
      name: "password"
      label: "Password"
      description: "Password for logging into IBM Db2 Warehouse as bluadmin user. Default password: changemeplease"
      type: "password"
      immutable: "false"
      required: true

pvcSettings:
  __metadata:
    label: "Storage (Persistent Volume) Configuration"
  useDynamicProvisioning:
    __metadata:
      name: "useDynamicProvisioning"
      label: "Use dynamic provisioning for persistent volume"
      description: "If dynamic provisioning is set, it will try to deploy on GlusterFS.  By default, it is not selected."
      type: "boolean"
      immutable: "false"
      required: false 
  volumeLabel:
    __metadata:
      name: "volumeLabel"
      label: "Storage (PV) Label"
      description: "Label is used as a key to select the Persistent Volume. If not selected, Kubernetes will select an available PV based on resource requirement"
      type: "string"
      immutable: "false"
      required: false
  volumeLabelValue:
    __metadata:
      name: "volumeLabelValue"
      label: "Storage (PV) Label Value"
      description: "Label Value is used as label's(key) value to select the Persistent Volume. If not selected, Kubernetes will select an available PV based on resource requirement"
      type: "string"
      immutable: "false"
      required: false
  storageClassName:
    __metadata:
      name: "storageClassName"
      label: "Storage Class Name"
      description: "Choose a specific storage class name. Defaults to the default storage class in the cluster"
      type: "string"
      immutable: "false"
      required: false
  existingClaimName:
    __metadata:
      name: "existingClaimName"
      label: "Existing Claim Name"
      description: "If a Persistent Volume Claim was explicitly created for the deployment, specify the name of the Persistent Volume Claim. If not provided, the deployment would automatically create a Persistent Volume Claim"
      type: "string"
      immutable: "false"
      required: false
  size:
    __metadata:
      name: "size"
      label: "Size of the the Volume Claim"
      description: "Specify a storage size for the persistent volume. By default, it is set to 25Gi (Gi = Gigabyte)"
      type: "string"
      immutable: true
      required: false

resources:
  __metadata:
    label: "Resource Configuration"
  requests:
    cpu:
      __metadata:
        label: "CPU"
        description: "Value for the CPU core. By default, it is set to a minimum value of 1000m (1000m = 1 core)"
        type: "string"
        required: true
    memory:
      __metadata:
        label: "Memory"
        description: "Value for the Memory. By default, it is set to a minimum value of 8Gi (Gi = Gigabyte)"
        type: "string"
        required: true
