{{ if (not .Values.pvcSettings.existingClaimName) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-pvc1
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.pvcSettings.useDynamicProvisioning }}
  storageClassName: {{ default nil .Values.pvcSettings.storageClassName | quote }}
  {{- else }}
  storageClassName: ""
  {{- end }}

  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.pvcSettings.size | quote }}
  {{- if and (not (empty .Values.pvcSettings.volumeLabel)) (not (empty .Values.pvcSettings.volumeLabelValue)) }}
  selector:
    matchLabels:
      {{ .Values.pvcSettings.volumeLabel }}: {{ .Values.pvcSettings.volumeLabelValue }}
  {{- end }}
{{- end }}
