###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2018. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
# Defines a service to allow internal access to the REST API
###############################################################################
{{ $namePrefix := .sch.chart.components.rest.service.name -}}
{{ $name := include "sch.names.fullCompName" (list . $namePrefix ) -}}
# Component is 'rest' as this makes up part of implementing the Admin REST API
{{ $compName := .sch.chart.components.rest.compName -}}
{{ $labels := include "sch.metadata.labels.standard" (list . $compName) -}}
{{ $deploymentName := .sch.chart.components.rest.deployment.name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ $labels | indent 4 }}
spec:
  ports:
    - port: {{ .sch.config.rest.ports.port  }}
      targetPort: {{ .sch.config.rest.ports.targetPort }}
      protocol: TCP
      name: http-port
  selector:
    release: {{ .Release.Name | quote }}
    serviceSelector: {{ $deploymentName | quote }}
